const NET={mode:'solo',peer:null,hostConn:null,conns:new Map(),localId:'p1',roomCode:'',ready:false,inputs:{},lobby:{p1:{id:'p1',cls:'warrior',name:'HOST'}},lastInputSend:0,lastSnapshot:0,clientTargets:null};
function netCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[(Math.random()*chars.length)|0];return s}
function netPeerId(code){return 'nexus-survival-'+String(code).toLowerCase()}
function netClose(){try{NET.hostConn?.close()}catch{};for(const c of NET.conns.values())try{c.close()}catch{};try{NET.peer?.destroy()}catch{};NET.peer=null;NET.hostConn=null;NET.conns.clear();NET.ready=false;NET.inputs={};NET.localId='p1';NET.lobby={p1:{id:'p1',cls:typeof cls!=='undefined'?cls:'warrior',name:'HOST'}};NET.clientTargets=null;NET.roomCode=''}
function netSetMode(mode){netClose();NET.mode=mode;document.querySelectorAll('.modeBtn').forEach(b=>b.classList.remove('sel'));const m={solo:'modeSolo',host:'modeHost',client:'modeJoin'}[mode];document.getElementById(m)?.classList.add('sel');document.getElementById('multiBox')?.classList.toggle('hidden',mode==='solo');document.getElementById('hostControls')?.classList.toggle('hidden',mode!=='host');document.getElementById('joinControls')?.classList.toggle('hidden',mode!=='client');const start=document.getElementById('start');if(start){start.disabled=mode!=='solo';start.textContent=mode==='host'?'CREATE ROOM // 방 생성 중':mode==='client'?'WAITING FOR HOST // 대기':'START RUN // 생존 시작'}if(mode==='host')netCreateHost();if(mode==='client')netRenderLobby();if(typeof menu==='function')menu()}
function netCreateHost(){if(typeof Peer==='undefined'){document.getElementById('hostStatus').textContent='PeerJS 로드 실패';return}const tryCreate=(attempt=0)=>{const code=netCode(),peer=new Peer(netPeerId(code));NET.peer=peer;NET.roomCode=code;peer.on('open',()=>{NET.ready=true;NET.lobby={p1:{id:'p1',cls:typeof cls!=='undefined'?cls:'warrior',name:'HOST'}};document.getElementById('roomCode').textContent=code;document.getElementById('hostStatus').textContent='방 생성 완료 · 참가자 대기 중';const start=document.getElementById('start');start.disabled=false;start.textContent='START MULTI RUN // 방 시작';netRenderLobby()});peer.on('connection',conn=>netAccept(conn));peer.on('error',err=>{if(err?.type==='unavailable-id'&&attempt<3){try{peer.destroy()}catch{};tryCreate(attempt+1)}else document.getElementById('hostStatus').textContent='네트워크 오류 · '+(err?.type||'unknown')})};tryCreate()}
function netAccept(conn){if(NET.conns.size>=3){conn.on('open',()=>conn.send({t:'full'}));return}conn.on('data',msg=>netHostMessage(conn,msg));conn.on('close',()=>{const pid=conn.playerId;if(pid){delete NET.lobby[pid];delete NET.inputs[pid]}NET.conns.delete(conn.peer);netBroadcastLobby()});conn.on('error',()=>{});NET.conns.set(conn.peer,conn)}
function netHostMessage(conn,msg){if(!msg||typeof msg!=='object')return;if(msg.t==='join'){const used=new Set(Object.keys(NET.lobby));let pid=['p2','p3','p4'].find(x=>!used.has(x));if(!pid){conn.send({t:'full'});return}conn.playerId=pid;NET.lobby[pid]={id:pid,cls:msg.cls||'warrior',name:'PLAYER '+pid.slice(1)};NET.inputs[pid]={};conn.send({t:'welcome',id:pid,room:NET.roomCode,lobby:NET.lobby,diff:typeof diff!=='undefined'?diff:'NORMAL'});netBroadcastLobby()}else if(msg.t==='input'&&conn.playerId){NET.inputs[conn.playerId]=msg.input||{}}else if(msg.t==='select'&&conn.playerId){if(NET.lobby[conn.playerId])NET.lobby[conn.playerId].cls=msg.cls;netBroadcastLobby()}else if(msg.t==='choice'&&conn.playerId&&typeof netApplyRemoteChoice==='function'){netApplyRemoteChoice(conn.playerId,msg.choice)}else if(msg.t==='ping'){conn.send({t:'pong',at:msg.at})}}
function netJoin(code){code=String(code||'').trim().toUpperCase();if(!code)return;netClose();NET.mode='client';NET.roomCode=code;document.getElementById('joinStatus').textContent='연결 중...';if(typeof Peer==='undefined'){document.getElementById('joinStatus').textContent='PeerJS 로드 실패';return}NET.peer=new Peer();NET.peer.on('open',()=>{const conn=NET.peer.connect(netPeerId(code),{reliable:true});NET.hostConn=conn;conn.on('open',()=>{NET.ready=true;document.getElementById('joinStatus').textContent='방장 응답 대기 중';conn.send({t:'join',cls:typeof cls!=='undefined'?cls:'warrior'})});conn.on('data',netClientMessage);conn.on('close',()=>{document.getElementById('joinStatus').textContent='방과 연결이 끊겼습니다';if(typeof endGame==='function'&&g)endGame('호스트와 연결이 끊겼습니다',false)});conn.on('error',()=>document.getElementById('joinStatus').textContent='연결 오류')});NET.peer.on('error',err=>document.getElementById('joinStatus').textContent='접속 실패 · '+(err?.type||'unknown'))}
function netClientMessage(msg){if(!msg||typeof msg!=='object')return;if(msg.t==='welcome'){NET.localId=msg.id;NET.lobby=msg.lobby||{};if(typeof diff!=='undefined')diff=msg.diff||diff;document.getElementById('joinStatus').textContent='접속 완료 · 방장이 시작하기를 기다리는 중';netRenderLobby();if(typeof menu==='function')menu()}else if(msg.t==='full'){document.getElementById('joinStatus').textContent='방이 가득 찼습니다'}else if(msg.t==='lobby'){NET.lobby=msg.lobby||NET.lobby;if(typeof diff!=='undefined')diff=msg.diff||diff;netRenderLobby();if(typeof menu==='function')menu()}else if(msg.t==='start'&&typeof clientStartFromNet==='function'){clientStartFromNet(msg.state)}else if(msg.t==='snap'&&typeof applyNetSnapshot==='function'){applyNetSnapshot(msg.state)}else if(msg.t==='level'&&typeof showClientLevel==='function'){showClientLevel(msg.choices)}else if(msg.t==='end'&&typeof endGame==='function'){endGame(msg.reason||'게임 종료',!!msg.victory,true)}else if(msg.t==='event'&&typeof applyNetEvent==='function'){applyNetEvent(msg.event)}}
function netBroadcast(data){for(const conn of NET.conns.values())if(conn.open)try{conn.send(data)}catch{}}
function netBroadcastLobby(){netBroadcast({t:'lobby',lobby:NET.lobby,diff:typeof diff!=='undefined'?diff:'NORMAL'});netRenderLobby()}
function netRenderLobby(){const el=document.getElementById('lobbyPlayers');if(!el)return;el.innerHTML='';Object.values(NET.lobby||{}).forEach(p=>{const d=document.createElement('span');d.className='lobbyChip '+(p.id===NET.localId?'me':'');const cname=(typeof C!=='undefined'&&C[p.cls])?C[p.cls].n:p.cls;d.textContent=`${p.name||p.id} · ${cname}`;el.appendChild(d)})}
function netClassChanged(newCls){if(NET.mode==='host'){if(NET.lobby.p1)NET.lobby.p1.cls=newCls;netBroadcastLobby()}else if(NET.mode==='client'&&NET.hostConn?.open){if(NET.lobby[NET.localId])NET.lobby[NET.localId].cls=newCls;NET.hostConn.send({t:'select',cls:newCls});netRenderLobby()}}
function netDifficultyChanged(){if(NET.mode==='host')netBroadcastLobby()}
function netInputFor(id){if(id==='p1')return {up:!!keys.KeyW,down:!!keys.KeyS,left:!!keys.KeyA,right:!!keys.KeyD};return NET.inputs[id]||{}}
function netSendInput(dt){if(NET.mode!=='client'||!NET.hostConn?.open)return;NET.lastInputSend-=dt;if(NET.lastInputSend<=0){NET.lastInputSend=.05;NET.hostConn.send({t:'input',input:{up:!!keys.KeyW,down:!!keys.KeyS,left:!!keys.KeyA,right:!!keys.KeyD}})}}
function netSendChoice(choice){if(NET.mode==='client'&&NET.hostConn?.open)NET.hostConn.send({t:'choice',choice})}
function netEmitEvent(event){if(NET.mode==='host')netBroadcast({t:'event',event})}
function netStartBroadcast(state){if(NET.mode==='host')netBroadcast({t:'start',state})}
function netSnapshotBroadcast(state){if(NET.mode==='host')netBroadcast({t:'snap',state})}
function netEndBroadcast(reason,victory){if(NET.mode==='host')netBroadcast({t:'end',reason,victory})}
window.addEventListener('DOMContentLoaded',()=>{
 document.getElementById('modeSolo').onclick=()=>netSetMode('solo');
 document.getElementById('modeHost').onclick=()=>netSetMode('host');
 document.getElementById('modeJoin').onclick=()=>netSetMode('client');
 document.getElementById('joinBtn').onclick=()=>netJoin(document.getElementById('roomInput').value);
 document.getElementById('roomInput').addEventListener('keydown',e=>{if(e.key==='Enter')netJoin(e.currentTarget.value)});
 document.getElementById('copyRoom').onclick=async()=>{try{await navigator.clipboard.writeText(NET.roomCode);document.getElementById('hostStatus').textContent='방 코드 복사 완료'}catch{}};
});
