const C={
 warrior:{n:'전사',d:'근접 광역 · 탱커',hp:190,spd:220,dmg:34,rate:.62,rng:110,col:'#d57357',icon:'⚔'},
 archer:{n:'궁수',d:'원거리 · 치명타',hp:125,spd:250,dmg:24,rate:.38,rng:430,col:'#7fb76a',icon:'➳'},
 mage:{n:'마법사',d:'광역 마법 · 제어',hp:110,spd:230,dmg:29,rate:.58,rng:365,col:'#7f8fd0',icon:'✦'},
 priest:{n:'성직자',d:'회복 · 신성 공격',hp:140,spd:225,dmg:23,rate:.50,rng:340,col:'#d8c779',icon:'✚'}
};
const DF={EASY:[.75,.8,.85,1.25],NORMAL:[1,1,1,1],HARD:[1.25,1.2,1.15,1],NIGHTMARE:[1.55,1.45,1.3,.95],HELL:[1.9,1.75,1.5,.9]};
const ST=[
 {name:'붕괴한 평원',boss:'오우거 대장',base:'#202b20',tile:'#2b3826',accent:'#758c50',enemy:['고블린','늑대','슬라임','고블린 궁수','폭탄병']},
 {name:'저주받은 늪',boss:'역병의 마녀',base:'#18251f',tile:'#23352c',accent:'#70874b',enemy:['독거미','늪지 좀비','박쥐','독성 슬라임','늪지 마법사']},
 {name:'얼어붙은 폐허',boss:'빙결의 거인',base:'#1d2b35',tile:'#2b414e',accent:'#7da4ac',enemy:['얼음 늑대','서리 해골','얼음 정령','설원 골렘','망령']},
 {name:'지옥의 요새',boss:'화염 군주',base:'#281b18',tile:'#3a241d',accent:'#a75c3c',enemy:['임프','지옥 사냥개','악마 전사','악마 궁수','화염 마법사']},
 {name:'공허의 균열',boss:'심연의 군주',base:'#17151f',tile:'#261f32',accent:'#8064a8',enemy:['공허 추적자','공허 벌레','심연의 눈','차원 암살자','공허 기사']}
];
const skills={warrior:['회전베기','지진강타','검기','방패 돌진','출혈 칼날','반격','투척 도끼','사슬 갈고리','광폭화','철벽'],archer:['다중 사격','관통 화살','화살비','독화살','저격','도탄 화살','폭발 화살','냉기 화살','속사','사냥꾼의 표식'],mage:['화염구','체인 라이트닝','얼음 폭발','운석','마력 구체','마력탄','비전 광선','눈보라','블랙홀','시간 왜곡'],priest:['신성한 빛','치유의 파동','신성 장판','천벌','보호막','신성 사슬','퇴마 구체','수호천사','기도','성광 폭발']};
const common=['공격력 +12%','공격속도 +10%','사거리 +12%','최대체력 +12%','이동속도 +10%','치명타 확률 +8%','획득 범위 +25%','체력 재생'];
let cls='warrior',diff='NORMAL',g=null,keys={},last=performance.now(),state='menu';
const $=x=>document.getElementById(x),cv=$('c'),ctx=cv.getContext('2d'),W=cv.width,H=cv.height;ctx.imageSmoothingEnabled=false;
function hash(x,y,s=0){let n=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return n-Math.floor(n)}
function menu(){let a=$('classes');a.innerHTML='';Object.entries(C).forEach(([k,v])=>{let b=document.createElement('button');b.className='classCard '+(k===cls?'sel':'');b.innerHTML=`<span class="pix">${v.icon}</span><b>${v.n}</b><small>${v.d}</small>`;b.onclick=()=>{cls=k;menu()};a.appendChild(b)});let d=$('diffs');d.innerHTML='';Object.keys(DF).forEach(k=>{let b=document.createElement('button');b.className='diffBtn '+(k===diff?'sel':'');b.textContent=k;b.onclick=()=>{diff=k;menu()};d.appendChild(b)})}menu();
function toast(t){let el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1400)}
function start(){let c=C[cls],f=DF[diff];g={t:0,stage:0,kills:0,boss:false,spawn:0,shake:0,p:{x:640,y:500,hp:c.hp,max:c.hp,spd:c.spd,dmg:c.dmg,rate:c.rate,rng:c.rng,at:0,l:1,xp:0,nxp:35,crit:.05,regen:0,skills:{},face:1,walk:0},n:{x:640,y:350,hp:2400*f[3],max:2400*f[3],lv:1,core:0,next:100,turret:0,regen:0,cd:0},e:[],q:[],gem:[],fx:[]};$('menu').classList.add('hidden');$('hud').classList.remove('hidden');state='play';toast('NEXUS DEFENSE // 시작')}
$('start').onclick=start;
function spawn(b=false){let f=DF[diff],a=Math.random()*Math.PI*2,r=520+Math.random()*220,x=g.n.x+Math.cos(a)*r,y=g.n.y+Math.sin(a)*r;if(b){g.e.push({x,y,r:46,hp:(4200+g.stage*2600)*f[0],max:(4200+g.stage*2600)*f[0],spd:50,dmg:(25+g.stage*10)*f[1],boss:true,cd:0,type:99,anim:Math.random()*10});g.boss=true;$('bosshud').classList.remove('hidden');$('bname').textContent=ST[g.stage].boss;toast('WARNING // '+ST[g.stage].boss);return}let type=(Math.random()*5)|0,baseR=[15,17,14,16,18][type];g.e.push({x,y,r:baseR,hp:(48+type*13+Math.random()*24)*(1+g.stage*.35)*f[0],max:100,spd:(72+Math.random()*48)*(type===1?1.15:1),dmg:(7+g.stage*4+type)*f[1],boss:false,cd:0,type,anim:Math.random()*10})}
function proj(x,y,tx,ty,dmg,source='player'){let a=Math.atan2(ty-y,tx-x),speed=source==='nexus'?430:560;g.q.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,d:dmg,life:1.3,source})}
function nearest(){let p=g.p,b=null,bd=p.rng*p.rng;for(let e of g.e){let d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<bd){bd=d;b=e}}return b}
function burst(x,y,col,n=5){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=40+Math.random()*100;g.fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.2,col})}}
function hit(e,d){let cr=Math.random()<g.p.crit;if(cr)d*=1.7;e.hp-=d;burst(e.x,e.y,cr?'#f4d67c':'#d8d3bf',cr?7:4);g.shake=Math.max(g.shake,cr?4:1.5);if(e.hp<=0){let i=g.e.indexOf(e);if(i>=0)g.e.splice(i,1);g.kills++;g.gem.push({x:e.x,y:e.y,v:e.boss?120:6,spin:Math.random()*6.28});burst(e.x,e.y,e.boss?'#e3a45f':'#8e5750',e.boss?24:8);if(e.boss){g.boss=false;$('bosshud').classList.add('hidden');openChest()}}}
function gain(v){let p=g.p;p.xp+=v;if(p.xp>=p.nxp){p.xp-=p.nxp;p.l++;p.nxp=Math.floor(35*Math.pow(p.l,1.18));levelUp()}}
function levelUp(){state='level';$('levelModal').classList.remove('hidden');let box=$('choices');box.innerHTML='';let classPool=[...skills[cls]].sort(()=>Math.random()-.5).slice(0,2).map(x=>({n:x,t:'CLASS SKILL'})),com=common[(Math.random()*common.length)|0],pool=[...classPool,{n:com,t:'COMMON'}].sort(()=>Math.random()-.5);pool.forEach(o=>{let b=document.createElement('button');b.className='choice';let lv=g.p.skills[o.n]||0;b.innerHTML=`<small>${o.t}</small><h3>${o.n}</h3><div class="lv">CURRENT LV.${lv}</div><p>${skills[cls].includes(o.n)?'직업 전용 능력을 강화합니다. 레벨이 오를수록 피해량과 발동 성능이 함께 증가합니다.':'모든 직업에 적용되는 기본 능력치를 강화합니다.'}</p>`;b.onclick=()=>choose(o.n);box.appendChild(b)})}
function choose(n){g.p.skills[n]=(g.p.skills[n]||0)+1;if(skills[cls].includes(n)){g.p.dmg*=1.075;g.p.rate*=.97}else{if(n.startsWith('공격력'))g.p.dmg*=1.12;else if(n.startsWith('공격속도'))g.p.rate*=.9;else if(n.startsWith('사거리'))g.p.rng*=1.12;else if(n.startsWith('최대체력')){g.p.max*=1.12;g.p.hp=g.p.max}else if(n.startsWith('이동속도'))g.p.spd*=1.1;else if(n.startsWith('치명타'))g.p.crit+=.08;else if(n.startsWith('체력 재생'))g.p.regen+=.006}$('levelModal').classList.add('hidden');state='play';toast('UPGRADE // '+n)}
$('nexusBtn').onclick=()=>{$('levelModal').classList.add('hidden');g.n.core+=100;if(g.n.core>=g.n.next){g.n.core-=g.n.next;g.n.lv++;g.n.next=Math.floor(100+(g.n.lv-1)*50);let r=Math.random();if(r<.34){g.n.max*=1.18;g.n.hp=Math.min(g.n.max,g.n.hp+g.n.max*.25);toast('NEXUS LV.'+g.n.lv+' // 외벽 강화')}else if(r<.67){g.n.turret++;toast('NEXUS LV.'+g.n.lv+' // 포탑 활성')}else{g.n.regen+=.0025;toast('NEXUS LV.'+g.n.lv+' // 자동 복구')}}state='play'};
function openChest(){state='chest';$('chestModal').classList.remove('hidden');let list=skills[cls],name=list[(Math.random()*list.length)|0];$('reward').innerHTML=`<b>${C[cls].n} 전용 보상</b><br>${name} 강화 모듈 획득`}
$('rewardBtn').onclick=()=>{$('chestModal').classList.add('hidden');if(g.stage>=4){alert('VICTORY // 심연의 군주를 처치했습니다');location.reload();return}g.stage++;g.t=0;g.e=[];g.q=[];g.gem=[];g.fx=[];g.n.hp=Math.min(g.n.max,g.n.hp+g.n.max*.2);state='play';toast('STAGE '+(g.stage+1)+' // '+ST[g.stage].name)};
function update(dt){if(state!=='play'||!g)return;dt=Math.min(dt,.033);g.t+=dt;let p=g.p,n=g.n,f=DF[diff],dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0),l=Math.hypot(dx,dy)||1;if(dx||dy){p.face=dx<0?-1:dx>0?1:p.face;p.walk+=dt*10}p.x=Math.max(28,Math.min(W-28,p.x+dx/l*p.spd*dt));p.y=Math.max(36,Math.min(H-28,p.y+dy/l*p.spd*dt));p.hp=Math.min(p.max,p.hp+p.max*p.regen*dt);n.hp=Math.min(n.max,n.hp+n.max*n.regen*dt);g.spawn-=dt;if(g.spawn<=0&&!g.boss){spawn();g.spawn=Math.max(.11,.68/(f[2]*(1+g.stage*.2)+g.t/170))}if(g.t>70&&!g.boss)spawn(true);p.at-=dt;if(p.at<=0){let e=nearest();if(e){proj(p.x,p.y-6,e.x,e.y,p.dmg);if((p.skills['다중 사격']||0)>0){for(let i=0;i<Math.min(3,p.skills['다중 사격']);i++)proj(p.x,p.y,e.x+Math.random()*54-27,e.y+Math.random()*54-27,p.dmg*.7)}p.at=p.rate}}for(let e of g.e){e.anim+=dt*7;let target=Math.hypot(p.x-e.x,p.y-e.y)<175?p:n,a=Math.atan2(target.y-e.y,target.x-e.x),ds=e.spd*dt;e.x+=Math.cos(a)*ds;e.y+=Math.sin(a)*ds;e.cd-=dt;if(Math.hypot(target.x-e.x,target.y-e.y)<e.r+24&&e.cd<=0){if(target===p){p.hp-=e.dmg;g.shake=5;if(p.hp<=0){alert('GAME OVER // 플레이어가 쓰러졌습니다');location.reload();return}}else{n.hp-=e.dmg;g.shake=6;if(n.hp<=0){alert('GAME OVER // NEXUS가 파괴되었습니다');location.reload();return}}e.cd=e.boss?.7:1.1}}for(let i=g.q.length-1;i>=0;i--){let q=g.q[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0){g.q.splice(i,1);continue}for(let e of g.e){if((q.x-e.x)**2+(q.y-e.y)**2<(e.r+7)**2){hit(e,q.d);g.q.splice(i,1);break}}}for(let i=g.gem.length-1;i>=0;i--){let z=g.gem[i],d=Math.hypot(p.x-z.x,p.y-z.y);z.spin+=dt*4;if(d<165){let a=Math.atan2(p.y-z.y,p.x-z.x);z.x+=Math.cos(a)*360*dt;z.y+=Math.sin(a)*360*dt}if(d<24){gain(z.v);g.gem.splice(i,1)}}if(n.turret>0){n.cd-=dt;if(n.cd<=0){let e=g.e[0];if(e)proj(n.x,n.y-8,e.x,e.y,18+n.turret*10,'nexus');n.cd=Math.max(.18,.8-n.turret*.08)}}for(let i=g.fx.length-1;i>=0;i--){let fz=g.fx[i];fz.x+=fz.vx*dt;fz.y+=fz.vy*dt;fz.vx*=.9;fz.vy*=.9;fz.life-=dt;if(fz.life<=0)g.fx.splice(i,1)}g.shake*=.86;hud()}
function hud(){let p=g.p,n=g.n;$('stage').textContent='STAGE '+(g.stage+1)+' // '+ST[g.stage].name;$('time').textContent=String((g.t/60)|0).padStart(2,'0')+':'+String(g.t%60|0).padStart(2,'0')+' · '+diff;$('enemyInfo').textContent='HOSTILES '+g.e.length;$('ntext').textContent=Math.max(0,n.hp|0)+' / '+(n.max|0);$('nbar').style.width=Math.max(0,n.hp/n.max*100)+'%';$('corebar').style.width=Math.min(100,n.core/n.next*100)+'%';$('core').textContent='CORE LV.'+n.lv+' · '+n.core+'/'+n.next+' · TURRET '+n.turret;$('pname').textContent=C[cls].n.toUpperCase();$('ptext').textContent=Math.max(0,p.hp|0)+' / '+(p.max|0);$('pbar').style.width=Math.max(0,p.hp/p.max*100)+'%';$('xbar').style.width=p.xp/p.nxp*100+'%';$('lvl').textContent='LEVEL '+p.l+' · ATK '+(p.dmg|0)+' · CRIT '+Math.round(p.crit*100)+'%';$('runData').textContent=g.kills+' KILLS';let tags=$('skillTags');tags.innerHTML='';Object.entries(p.skills).slice(0,5).forEach(([k,v])=>{let s=document.createElement('span');s.className='skillTag';s.textContent=k+' '+v;tags.appendChild(s)});let b=g.e.find(x=>x.boss);if(b){$('btext').textContent=Math.max(0,b.hp|0)+' / '+(b.max|0);$('bbar').style.width=Math.max(0,b.hp/b.max*100)+'%'}}
