const VIEW={w:1280,h:720},WORLD={w:2600,h:1800};
const C={
 warrior:{n:'전사',d:'근접 광역 · 탱커',hp:210,spd:220,dmg:38,rate:.62,rng:125,col:'#d57357',icon:'⚔'},
 archer:{n:'궁수',d:'원거리 · 치명타',hp:135,spd:255,dmg:25,rate:.38,rng:470,col:'#7fb76a',icon:'➳'},
 mage:{n:'마법사',d:'광역 마법 · 제어',hp:120,spd:235,dmg:30,rate:.58,rng:390,col:'#7f8fd0',icon:'✦'},
 priest:{n:'성직자',d:'회복 · 신성 공격',hp:155,spd:230,dmg:25,rate:.50,rng:360,col:'#d8c779',icon:'✚'}
};
const DF={EASY:[.75,.8,.85,1.25],NORMAL:[1,1,1,1],HARD:[1.25,1.2,1.15,1],NIGHTMARE:[1.55,1.45,1.3,.95],HELL:[1.9,1.75,1.5,.9]};
const PARTY={1:[1,1,1],2:[1.45,1.25,1.65],3:[1.9,1.48,2.25],4:[2.3,1.72,2.85]};
const ST=[
 {name:'붕괴한 평원',boss:'오우거 대장',base:'#202b20',tile:'#2b3826',accent:'#758c50',enemy:['고블린','늑대','슬라임','고블린 궁수','폭탄병']},
 {name:'저주받은 늪',boss:'역병의 마녀',base:'#18251f',tile:'#23352c',accent:'#70874b',enemy:['독거미','늪지 좀비','박쥐','독성 슬라임','늪지 마법사']},
 {name:'얼어붙은 폐허',boss:'빙결의 거인',base:'#1d2b35',tile:'#2b414e',accent:'#7da4ac',enemy:['얼음 늑대','서리 해골','얼음 정령','설원 골렘','망령']},
 {name:'지옥의 요새',boss:'화염 군주',base:'#281b18',tile:'#3a241d',accent:'#a75c3c',enemy:['임프','지옥 사냥개','악마 전사','악마 궁수','화염 마법사']},
 {name:'공허의 균열',boss:'심연의 군주',base:'#17151f',tile:'#261f32',accent:'#8064a8',enemy:['공허 추적자','공허 벌레','심연의 눈','차원 암살자','공허 기사']}
];
const sd=(n,desc,kind='active')=>({n,desc,kind,max:5});
const SK={
 warrior:{
 W01:sd('회전베기','주기적으로 검을 크게 휘둘러 주변 모든 적에게 피해를 줍니다.'),W02:sd('지진강타','대지를 내려쳐 넓은 충격파를 만들고 적을 둔화합니다.'),W03:sd('검기','가장 가까운 적 방향으로 관통하는 검기를 발사합니다.'),W04:sd('방패 돌진','적 방향으로 짧게 돌진하며 경로의 적을 타격하고 보호막을 얻습니다.'),W05:sd('전쟁의 도발','주변 적의 공격 대상을 자신으로 바꾸고 잠시 받는 피해를 줄입니다.'),W06:sd('출혈 칼날','기본 공격이 일정 확률로 출혈을 걸어 지속 피해를 줍니다.','passive'),W07:sd('반격','피해를 받았을 때 일정 확률로 주변 적에게 즉시 반격합니다.','passive'),W08:sd('투척 도끼','회전하는 도끼 여러 개를 사방으로 던집니다.'),W09:sd('사슬 갈고리','가장 강한 적을 끌어당기며 피해를 줍니다.'),W10:sd('분쇄파','기본 공격을 여러 번 적중하면 추가 충격파가 발생합니다.','passive'),W11:sd('광폭화','체력이 낮을수록 공격력과 공격속도가 증가합니다.','passive'),W12:sd('철벽','일정 시간마다 최대 체력에 비례한 보호막을 생성합니다.'),W13:sd('전투 함성','주기적으로 자신과 모든 파티원의 공격력을 증가시킵니다.'),W14:sd('수호진','넥서스 주변에 적에게 피해를 주고 아군 피해를 줄이는 수호 영역을 만듭니다.'),W15:sd('처형 베기','가장 강한 적에게 큰 피해를 주며 체력이 낮은 적에게 추가 피해를 줍니다.')},
 archer:{
 A01:sd('다중 사격','기본 공격 시 추가 화살을 함께 발사합니다.','passive'),A02:sd('관통 화살','기본 화살이 여러 적을 관통합니다.','passive'),A03:sd('화살비','적이 밀집한 지역에 지속적으로 화살이 떨어지는 영역을 만듭니다.'),A04:sd('독화살','기본 화살이 적에게 중독을 부여해 지속 피해를 줍니다.','passive'),A05:sd('저격','가장 강한 적에게 치명타 확률이 높은 강력한 화살을 발사합니다.'),A06:sd('도탄 화살','화살이 적중한 뒤 주변 적에게 추가로 튕깁니다.','passive'),A07:sd('폭발 화살','기본 화살 적중 시 작은 폭발을 일으켜 주변 적에게 피해를 줍니다.','passive'),A08:sd('냉기 화살','기본 화살이 적의 이동속도를 감소시킵니다.','passive'),A09:sd('속사','주기적으로 짧은 시간 동안 공격속도가 크게 증가합니다.'),A10:sd('사냥꾼의 표식','가장 강한 적에게 표식을 남겨 파티가 주는 피해를 증가시킵니다.'),A11:sd('매 소환','매가 플레이어 주변을 돌며 주기적으로 적에게 화살을 발사합니다.'),A12:sd('가시 덫','이동 경로에 덫을 설치해 밟은 적에게 피해와 둔화를 줍니다.'),A13:sd('회귀 화살','전방으로 날아갔다 되돌아오는 큰 화살을 발사합니다.'),A14:sd('연쇄 사격','적 처치 시 일정 확률로 가까운 적에게 추가 화살이 발사됩니다.','passive'),A15:sd('폭풍 화살','넓은 지역에 화살과 번개가 연속해서 떨어지는 폭풍을 만듭니다.')},
 mage:{
 M01:sd('화염구','폭발하는 화염구를 발사해 주변 적에게 화상 피해를 줍니다.'),M02:sd('체인 라이트닝','번개가 여러 적 사이를 연쇄하며 즉시 피해를 줍니다.'),M03:sd('얼음 폭발','주변 적을 얼어붙게 하는 냉기 폭발을 일으킵니다.'),M04:sd('운석','잠시 후 목표 지점에 거대한 운석이 떨어져 강한 광역 피해를 줍니다.'),M05:sd('마력 구체','마력 구체가 플레이어 주변을 회전하며 가까운 적을 공격합니다.'),M06:sd('마력탄','추적하는 마력탄 여러 개를 동시에 발사합니다.'),M07:sd('비전 광선','가장 가까운 적 방향으로 긴 광선을 발사해 직선상의 적을 타격합니다.'),M08:sd('눈보라','넓은 지역에 눈보라를 만들어 지속 피해와 강한 둔화를 줍니다.'),M09:sd('화염벽','적과 넥서스 사이에 화염벽을 생성해 통과하는 적을 태웁니다.'),M10:sd('뇌우','주변 무작위 적들에게 연속해서 번개를 떨어뜨립니다.'),M11:sd('블랙홀','적을 중심으로 끌어당기며 지속 피해를 주는 블랙홀을 생성합니다.'),M12:sd('서리창','여러 적을 관통하고 강한 둔화를 거는 거대한 서리창을 발사합니다.'),M13:sd('비전 지뢰','플레이어 주변에 마력 지뢰를 설치해 접근한 적에게 폭발 피해를 줍니다.'),M14:sd('원소 정령','원소 정령이 주기적으로 화염·냉기·번개 공격을 사용합니다.'),M15:sd('시간 왜곡','주변의 적 이동속도를 크게 낮추는 시간 영역을 만듭니다.')},
 priest:{
 P01:sd('신성한 빛','가까운 적에게 신성한 빛을 내려 꽂아 피해를 줍니다.'),P02:sd('치유의 파동','자신과 주변 파티원의 체력을 회복합니다.'),P03:sd('신성 장판','아군은 회복하고 적은 피해를 받는 신성 영역을 생성합니다.'),P04:sd('천벌','강한 적을 중심으로 신성 낙뢰를 떨어뜨려 큰 피해를 줍니다.'),P05:sd('보호막','자신과 체력이 낮은 파티원에게 보호막을 부여합니다.'),P06:sd('신성 사슬','신성 에너지가 여러 적을 연결하며 연쇄 피해와 둔화를 줍니다.'),P07:sd('퇴마 구체','신성 구체가 플레이어 주변을 돌며 적에게 피해를 줍니다.'),P08:sd('수호천사','치명적인 피해를 한 번 막고 체력을 회복합니다. 재사용 대기시간이 있습니다.','passive'),P09:sd('기도','파티 전체의 공격력과 이동속도를 일정 시간 증가시킵니다.'),P10:sd('신성창','직선상의 적을 관통하는 신성한 창을 발사합니다.'),P11:sd('정화의 불꽃','주변 적을 태우고 자신에게 걸린 둔화 효과를 제거합니다.'),P12:sd('찬송가','자신과 가까운 파티원의 체력을 지속적으로 회복합니다.','passive'),P13:sd('심판의 낙인','강한 적에게 낙인을 새겨 받는 피해를 증가시킵니다.'),P14:sd('성역','아군이 받는 피해를 줄이고 체력을 회복하는 넓은 성역을 생성합니다.'),P15:sd('성광 폭발','플레이어 주변에 대규모 신성 폭발을 일으켜 적을 밀어내고 피해를 줍니다.')}
};
const COMMON={C01:{n:'힘',desc:'공격력 +12%'},C02:{n:'신속',desc:'공격속도 +10%'},C03:{n:'장거리 전투',desc:'공격 사거리 +12%'},C04:{n:'강인함',desc:'최대 체력 +12%'},C05:{n:'기동력',desc:'이동속도 +10%'},C06:{n:'행운',desc:'치명타 확률 +8%'},C07:{n:'자석',desc:'경험치 획득 범위 +25%'},C08:{n:'재생',desc:'초당 최대 체력 0.6% 회복'}};
let cls='warrior',diff='NORMAL',g=null,keys={},last=performance.now(),state='menu',choiceOwner=null;
const $=x=>document.getElementById(x),cv=$('c'),ctx=cv.getContext('2d'),W=cv.width,H=cv.height;ctx.imageSmoothingEnabled=false;
function allSkillIds(c){return Object.keys(SK[c])} function skillDef(c,id){return SK[c]?.[id]} function hash(x,y,s=0){let n=Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453;return n-Math.floor(n)}
function menu(){const a=$('classes');a.innerHTML='';Object.entries(C).forEach(([k,v])=>{let b=document.createElement('button');b.className='classCard '+(k===cls?'sel':'');b.innerHTML=`<span class="pix">${v.icon}</span><b>${v.n}</b><small>${v.d}</small>`;b.onclick=()=>{cls=k;if(NET.mode==='client'&&NET.lobby[NET.localId])NET.lobby[NET.localId].cls=k;if(NET.mode==='host'&&NET.lobby.p1)NET.lobby.p1.cls=k;netClassChanged(k);menu()};a.appendChild(b)});const d=$('diffs');d.innerHTML='';Object.keys(DF).forEach(k=>{let b=document.createElement('button');b.className='diffBtn '+(k===diff?'sel':'');b.textContent=k;b.disabled=NET.mode==='client';b.onclick=()=>{diff=k;netDifficultyChanged();menu()};d.appendChild(b)});if(NET.mode==='client'&&NET.lobby[NET.localId]?.cls&&NET.lobby[NET.localId].cls!==cls)cls=NET.lobby[NET.localId].cls;netRenderLobby()}
function toast(t){let el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1400)}
function makePlayer(id,c,x,y){let s=C[c];return{id,cls:c,x,y,tx:x,ty:y,hp:s.hp,max:s.hp,spd:s.spd,dmg:s.dmg,rate:s.rate,rng:s.rng,at:0,l:1,xp:0,nxp:35,crit:.05,regen:0,pickup:170,skills:{},cd:{},face:1,walk:0,shield:0,damageReduce:0,atkBuff:1,atkBuffUntil:0,speedBuff:1,speedBuffUntil:0,guardianCd:0,hitCount:0,alive:true,pendingLevel:false}}
function partyCount(){return g?Object.keys(g.players).length:Math.max(1,Object.keys(NET.lobby||{}).length)}
function createRunFromLobby(){let f=DF[diff],members=NET.mode==='solo'?{p1:{id:'p1',cls,name:'SOLO'}}:NET.lobby;const ids=Object.keys(members);let players={};ids.forEach((id,i)=>{let a=i*Math.PI*2/Math.max(1,ids.length)+Math.PI/2;players[id]=makePlayer(id,members[id].cls||'warrior',WORLD.w/2+Math.cos(a)*150,WORLD.h/2+Math.sin(a)*150)});return{t:0,stage:0,kills:0,boss:false,spawn:0,shake:0,nextEnemyId:1,players,localId:NET.localId||'p1',n:{x:WORLD.w/2,y:WORLD.h/2,hp:2600*f[3],max:2600*f[3],lv:1,core:0,next:100,turret:0,regen:0,cd:0},e:[],q:[],gem:[],fx:[],text:[],zones:[],delayed:[],cam:{x:0,y:0},snapCd:0}}
function startRun(){if(NET.mode==='client')return;g=createRunFromLobby();$('menu').classList.add('hidden');$('hud').classList.remove('hidden');state='play';if(NET.mode==='host')netStartBroadcast(makeNetState());toast(`NEXUS DEFENSE // ${partyCount()}인 시작`)} $('start').onclick=()=>{if(NET.mode==='host'&&!NET.ready)return;startRun()};
function clientStartFromNet(s){g={t:0,stage:0,kills:0,boss:false,spawn:0,shake:0,players:{},localId:NET.localId,n:{},e:[],q:[],gem:[],fx:[],text:[],zones:[],delayed:[],cam:{x:0,y:0}};applyNetSnapshot(s,true);$('menu').classList.add('hidden');$('hud').classList.remove('hidden');state='play';toast('MULTI LINK // 전투 시작')}
function randEdgeSpawn(){let a=Math.random()*Math.PI*2,r=820+Math.random()*300,n=g.n;return{x:Math.max(30,Math.min(WORLD.w-30,n.x+Math.cos(a)*r)),y:Math.max(30,Math.min(WORLD.h-30,n.y+Math.sin(a)*r))}}
function spawn(b=false){let f=DF[diff],pc=partyCount(),ps=PARTY[pc]||PARTY[4],pos=randEdgeSpawn();if(b){let hp=(4700+g.stage*3000)*f[0]*ps[2];g.e.push({id:g.nextEnemyId++,x:pos.x,y:pos.y,tx:pos.x,ty:pos.y,r:48,hp,max:hp,spd:52,dmg:(26+g.stage*10)*f[1],boss:true,cd:0,type:99,anim:Math.random()*10,slow:1,slowUntil:0,dotTick:0,markedUntil:0});g.boss=true;$('bosshud').classList.remove('hidden');$('bname').textContent=ST[g.stage].boss;toast('WARNING // '+ST[g.stage].boss);return}let type=(Math.random()*5)|0,baseR=[15,17,14,16,18][type],hp=(52+type*14+Math.random()*28)*(1+g.stage*.36)*f[0]*ps[0];g.e.push({id:g.nextEnemyId++,x:pos.x,y:pos.y,tx:pos.x,ty:pos.y,r:baseR,hp,max:hp,spd:(74+Math.random()*50)*(type===1?1.15:1),dmg:(7+g.stage*4+type)*f[1],boss:false,cd:0,type,anim:Math.random()*10,slow:1,slowUntil:0,dotTick:0,markedUntil:0,poison:0,poisonUntil:0,burn:0,burnUntil:0,targetPlayer:null})}
function playerById(id){return g.players[id]} function localPlayer(){return g?.players?.[g.localId]||g?.players?.p1}
function nearestEnemy(p,range=p.rng){let b=null,bd=range*range;for(let e of g.e){if(e.dead)continue;let d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<bd){bd=d;b=e}}return b}
function strongestEnemy(range=99999,p=localPlayer()){let b=null,score=-1;for(let e of g.e){let d=Math.hypot(e.x-p.x,e.y-p.y);if(d<=range&&e.hp>score){score=e.hp;b=e}}return b}
function enemiesIn(x,y,r){let rr=r*r;return g.e.filter(e=>!e.dead&&(e.x-x)**2+(e.y-y)**2<=rr)}
function addFx(type,x,y,o={}){let fx={type,x,y,life:o.life??.45,max:o.life??.45,r:o.r??40,r2:o.r2??o.r??40,col:o.col||'#ffffff',angle:o.angle||0,ownerId:o.ownerId||null};g.fx.push(fx);if(NET.mode==='host'&&o.net!==false)netEmitEvent({k:'fx',fx})}
function addText(x,y,value,kind='enemy',crit=false,net=true){let t={x,y,value:Math.round(value),kind,crit,life:.75,max:.75,vy:-45};g.text.push(t);if(NET.mode==='host'&&net)netEmitEvent({k:'text',t})}
function burst(x,y,col,n=5){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=40+Math.random()*100;g.fx.push({type:'particle',x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.2,max:.4,col,r:2})}}
function basicMods(p){return{pierce:p.skills.A02||0,poison:p.skills.A04||0,explode:p.skills.A07||0,slow:p.skills.A08||0,ricochet:p.skills.A06||0}}
function proj(p,tx,ty,dmg,o={}){let a=Math.atan2(ty-p.y,tx-p.x),speed=o.speed||560;g.q.push({x:p.x,y:p.y-6,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,d:dmg,life:o.life||1.6,ownerId:p.id,source:o.source||'player',col:o.col||C[p.cls].col,size:o.size||5,pierce:o.pierce||0,poison:o.poison||0,explode:o.explode||0,slow:o.slow||0,ricochet:o.ricochet||0,returning:o.returning||false,returned:false,homing:o.homing||0,skill:o.skill||null,hitIds:[]})}
function damageEnemy(e,amount,ownerId,o={}){if(!e||e.dead)return 0;let p=playerById(ownerId)||localPlayer(),crit=o.crit===true||(o.crit!==false&&Math.random()<(p?.crit||0)),d=amount*(p?.atkBuff||1);if(e.markedUntil>g.t)d*=1.18;if(crit)d*=1.7;e.hp-=d;addText(e.x,e.y-e.r-8,d,'enemy',crit);burst(e.x,e.y,crit?'#f0cf6f':'#d8d3bf',crit?6:3);if(o.poison){e.poison=Math.max(e.poison,(p?.dmg||20)*(.10+.05*o.poison));e.poisonUntil=g.t+4+o.poison}if(o.burn){e.burn=Math.max(e.burn,(p?.dmg||20)*(.12+.05*o.burn));e.burnUntil=g.t+3+o.burn*.5}if(o.slow){e.slow=Math.min(e.slow,.82-.05*o.slow);e.slowUntil=g.t+2+o.slow*.25}if(e.hp<=0)killEnemy(e,ownerId);return d}
function killEnemy(e,ownerId){if(e.dead)return;e.dead=true;g.kills++;g.gem.push({x:e.x,y:e.y,v:e.boss?140:6,spin:Math.random()*6.28});burst(e.x,e.y,e.boss?'#e3a45f':'#8e5750',e.boss?24:8);let p=playerById(ownerId);if(p?.skills.A14&&Math.random()<.25+.08*p.skills.A14){let n=nearestEnemy(p,520);if(n)proj(p,n.x,n.y,p.dmg*(.7+.08*p.skills.A14),{col:'#b8e28e',skill:'A14'})}if(e.boss){g.boss=false;$('bosshud').classList.add('hidden');openChest()}}
function areaDamage(x,y,r,dmg,ownerId,o={}){addFx(o.fx||'ring',x,y,{r,col:o.col||'#e9ddbb',life:o.life||.35,ownerId});for(let e of enemiesIn(x,y,r))damageEnemy(e,dmg,ownerId,o)}
function lineDamage(x,y,tx,ty,width,dmg,ownerId,o={}){let dx=tx-x,dy=ty-y,len=Math.hypot(dx,dy)||1,nx=dx/len,ny=dy/len;addFx(o.fx||'beam',x,y,{r:len,r2:width,col:o.col||'#fff',angle:Math.atan2(dy,dx),life:o.life||.28,ownerId});for(let e of g.e){let px=e.x-x,py=e.y-y,t=Math.max(0,Math.min(len,px*nx+py*ny)),cx=x+nx*t,cy=y+ny*t;if(Math.hypot(e.x-cx,e.y-cy)<width+e.r)damageEnemy(e,dmg,ownerId,o)}}
function chainDamage(first,count,dmg,ownerId,o={}){let cur=first,hit=[];for(let i=0;i<count&&cur;i++){damageEnemy(cur,dmg*(1-i*.08),ownerId,o);hit.push(cur.id);let from=cur;cur=null,bd=220*220;for(let e of g.e){if(hit.includes(e.id)||e.dead)continue;let d=(e.x-from.x)**2+(e.y-from.y)**2;if(d<bd){bd=d;cur=e}}if(cur)addFx('lightning',from.x,from.y,{r:Math.hypot(cur.x-from.x,cur.y-from.y),angle:Math.atan2(cur.y-from.y,cur.x-from.x),col:o.col||'#a7d9ff',life:.18,ownerId})}}
function addZone(type,x,y,r,life,ownerId,dmg=0,o={}){let z={type,x,y,r,life,max:life,ownerId,dmg,tick:0,col:o.col||'#fff',heal:o.heal||0,slow:o.slow||0,pull:o.pull||0,trigger:o.trigger||false};g.zones.push(z);addFx(type,x,y,{r,col:z.col,life:.4,ownerId})}
function damagePlayer(p,amount){if(!p||!p.alive)return;let d=amount*Math.max(.25,1-(p.damageReduce||0));if(p.shield>0){let used=Math.min(p.shield,d);p.shield-=used;d-=used;if(used>0)addText(p.x,p.y-38,used,'shield',false)}if(d<=0)return;if(p.guardianCd<=0&&(p.skills.P08||0)>0&&p.hp-d<=0){p.hp=Math.max(p.max*(.18+.04*p.skills.P08),1);p.guardianCd=Math.max(28,60-6*p.skills.P08);addFx('holy',p.x,p.y,{r:80,col:'#fff0a6'});addText(p.x,p.y-42,0,'guard',false);return}p.hp-=d;addText(p.x,p.y-38,d,'player',false);g.shake=Math.max(g.shake,4);if((p.skills.W07||0)>0&&Math.random()<.18+.06*p.skills.W07)areaDamage(p.x,p.y,75+8*p.skills.W07,p.dmg*(.8+.18*p.skills.W07),p.id,{fx:'counter',col:'#f0b18d'});if(p.hp<=0){p.hp=0;p.alive=false;let alive=Object.values(g.players).some(x=>x.alive);if(!alive)endGame('모든 플레이어가 쓰러졌습니다',false)}}
function damageNexus(amount){g.n.hp-=amount;addText(g.n.x,g.n.y-65,amount,'nexus',false);g.shake=Math.max(g.shake,6);if(g.n.hp<=0){g.n.hp=0;endGame('NEXUS가 파괴되었습니다',false)}}
function healPlayer(p,amount){if(!p||!p.alive)return;let before=p.hp;p.hp=Math.min(p.max,p.hp+amount);let v=p.hp-before;if(v>1)addText(p.x,p.y-36,v,'heal',false)}
function gainPartyXp(v){for(let p of Object.values(g.players)){if(!p.alive)continue;p.xp+=v;while(p.xp>=p.nxp&&!p.pendingLevel){p.xp-=p.nxp;p.l++;p.nxp=Math.floor(35*Math.pow(p.l,1.18));requestLevel(p);break}}}
function makeChoices(p){let ids=allSkillIds(p.cls).filter(id=>(p.skills[id]||0)<5),chosen=[...ids].sort(()=>Math.random()-.5).slice(0,2).map(id=>({type:'skill',id}));let cids=Object.keys(COMMON),cid=cids[(Math.random()*cids.length)|0];chosen.push({type:'common',id:cid});return chosen.sort(()=>Math.random()-.5)}
function skillNextText(p,id){let lv=p.skills[id]||0;if(lv>=5)return'MAX LEVEL';let next=lv+1,m={W01:'범위와 피해 증가',W02:'충격파 범위·둔화 증가',W03:'검기 피해·관통 증가',W04:'돌진 피해·보호막 증가',W05:'도발 범위·피해 감소 증가',W06:'출혈 확률·피해 증가',W07:'반격 확률·범위 증가',W08:'도끼 수·피해 증가',W09:'사거리·끌어당김 증가',W10:'충격파 발동 간격 감소',W11:'저체력 공격 보너스 증가',W12:'보호막량 증가',W13:'파티 공격력 증가',W14:'수호 영역 범위·피해 증가',W15:'처형 피해·보스 피해 증가',A01:'추가 화살 수 증가',A02:'관통 횟수 증가',A03:'화살비 범위·피해 증가',A04:'중독 피해·지속시간 증가',A05:'저격 피해·치명타 보너스 증가',A06:'도탄 횟수 증가',A07:'폭발 범위·피해 증가',A08:'둔화 강도 증가',A09:'속사 지속시간 증가',A10:'표식 피해 증폭 증가',A11:'매 공격속도·피해 증가',A12:'덫 수·피해 증가',A13:'회귀 화살 크기·피해 증가',A14:'처치 연쇄 확률 증가',A15:'폭풍 범위·낙하 횟수 증가',M01:'화염구 폭발·화상 증가',M02:'연쇄 대상 수 증가',M03:'빙결 범위·둔화 증가',M04:'운석 범위·피해 증가',M05:'마력 구체 수 증가',M06:'마력탄 수 증가',M07:'광선 폭·피해 증가',M08:'눈보라 범위·지속 증가',M09:'화염벽 길이·피해 증가',M10:'낙뢰 횟수 증가',M11:'블랙홀 흡입력·범위 증가',M12:'서리창 수·관통 증가',M13:'지뢰 수·폭발 범위 증가',M14:'정령 공격력·공격속도 증가',M15:'시간 왜곡 범위·감속 증가',P01:'신성한 빛 대상 수 증가',P02:'회복량·범위 증가',P03:'장판 피해·회복 증가',P04:'천벌 피해·범위 증가',P05:'보호막량·대상 수 증가',P06:'신성 사슬 연쇄 수 증가',P07:'퇴마 구체 수 증가',P08:'수호천사 재사용시간 감소',P09:'파티 버프 증가',P10:'신성창 수·관통 증가',P11:'정화의 불꽃 범위·화상 증가',P12:'지속 회복량 증가',P13:'낙인 피해 증폭 증가',P14:'성역 피해 감소·회복 증가',P15:'성광 폭발 범위·피해 증가'}[id]||'효과 강화';return `Lv.${next} → ${m}`}
function requestLevel(p){p.pendingLevel=true;let choices=makeChoices(p);if(p.id===g.localId)showLevelChoices(p,choices);else if(NET.mode==='host'){let conn=[...NET.conns.values()].find(c=>c.playerId===p.id);if(conn?.open)conn.send({t:'level',choices})}}
function showLevelChoices(p,choices){choiceOwner=p.id;if(NET.mode==='solo')state='level';$('levelModal').classList.remove('hidden');let box=$('choices');box.innerHTML='';choices.forEach(o=>{let b=document.createElement('button');b.className='choice';if(o.type==='skill'){let d=skillDef(p.cls,o.id),lv=p.skills[o.id]||0;b.innerHTML=`<small>CLASS SKILL</small><h3>${d.n}</h3><div class="lv">CURRENT LV.${lv}</div><p>${d.desc}</p><div class="next">${skillNextText(p,o.id)}</div>`}else{let d=COMMON[o.id];b.innerHTML=`<small>COMMON</small><h3>${d.n}</h3><div class="lv">공통 패시브</div><p>${d.desc}</p><div class="next">선택 즉시 기본 능력치에 적용</div>`}b.onclick=()=>selectChoice(o);box.appendChild(b)})}
function showClientLevel(choices){let p=localPlayer();if(p){p.pendingLevel=true;showLevelChoices(p,choices)}}
function selectChoice(o){$('levelModal').classList.add('hidden');if(NET.mode==='client'){netSendChoice(o);localPlayer().pendingLevel=false;choiceOwner=null;return}let p=playerById(choiceOwner)||localPlayer();applyChoice(p,o);p.pendingLevel=false;choiceOwner=null;if(NET.mode==='solo')state='play'}
function applyChoice(p,o){if(o.type==='skill'){p.skills[o.id]=(p.skills[o.id]||0)+1;toast('UPGRADE // '+skillDef(p.cls,o.id).n)}else{if(o.id==='C01')p.dmg*=1.12;else if(o.id==='C02')p.rate*=.9;else if(o.id==='C03')p.rng*=1.12;else if(o.id==='C04'){p.max*=1.12;p.hp=p.max}else if(o.id==='C05')p.spd*=1.1;else if(o.id==='C06')p.crit+=.08;else if(o.id==='C07')p.pickup*=1.25;else if(o.id==='C08')p.regen+=.006;toast('COMMON // '+COMMON[o.id].n)}}
function netApplyRemoteChoice(pid,o){let p=playerById(pid);if(!p)return;if(o?.type==='nexus')investNexus();else applyChoice(p,o);p.pendingLevel=false}
$('nexusBtn').onclick=()=>{$('levelModal').classList.add('hidden');if(NET.mode==='client'){netSendChoice({type:'nexus'});let p=localPlayer();if(p)p.pendingLevel=false;return}investNexus();let p=playerById(choiceOwner)||localPlayer();if(p)p.pendingLevel=false;choiceOwner=null;if(NET.mode==='solo')state='play'};
function investNexus(){g.n.core+=100;if(g.n.core>=g.n.next){g.n.core-=g.n.next;g.n.lv++;g.n.next=Math.floor(100+(g.n.lv-1)*50)*({1:1,2:1.7,3:2.3,4:2.8}[partyCount()]||2.8);let r=Math.random();if(r<.34){g.n.max*=1.16;g.n.hp=Math.min(g.n.max,g.n.hp+g.n.max*.28);toast('NEXUS LV.'+g.n.lv+' // 외벽 강화')}else if(r<.67){g.n.turret++;toast('NEXUS LV.'+g.n.lv+' // 포탑 활성')}else{g.n.regen+=.0025;toast('NEXUS LV.'+g.n.lv+' // 자동 복구')}}}
function openChest(){if(NET.mode==='client')return;state=NET.mode==='solo'?'chest':'play';$('chestModal').classList.remove('hidden');let p=localPlayer(),ids=allSkillIds(p.cls),id=ids[(Math.random()*ids.length)|0],d=skillDef(p.cls,id);$('reward').innerHTML=`<b>${C[p.cls].n} 전용 보상</b><br>${d.n} 강화 모듈 획득<br><small>${d.desc}</small>`;g.pendingChestSkill=id}
$('rewardBtn').onclick=()=>{if(!g)return;$('chestModal').classList.add('hidden');let p=localPlayer();if(g.pendingChestSkill&&p&&(p.skills[g.pendingChestSkill]||0)<5)p.skills[g.pendingChestSkill]=(p.skills[g.pendingChestSkill]||0)+1;if(g.stage>=4){endGame('심연의 군주를 처치하고 넥서스를 지켜냈습니다',true);return}advanceStage();if(NET.mode==='solo')state='play'};
function advanceStage(){g.stage++;g.t=0;g.e=[];g.q=[];g.gem=[];g.fx=[];g.text=[];g.zones=[];g.delayed=[];g.boss=false;g.n.hp=Math.min(g.n.max,g.n.hp+g.n.max*.22);for(let p of Object.values(g.players)){p.x=g.n.x+(Math.random()-.5)*240;p.y=g.n.y+170+(Math.random()-.5)*120;p.tx=p.x;p.ty=p.y;p.alive=true;p.hp=Math.max(p.hp,p.max*.4)}toast('STAGE '+(g.stage+1)+' // '+ST[g.stage].name)}
function cdReady(p,id,base,dt){p.cd[id]=(p.cd[id]??Math.random()*base)-dt;if(p.cd[id]<=0){let lv=p.skills[id]||0;p.cd[id]=Math.max(.25,base*(1-.035*lv));return true}return false}
function runSkills(p,dt){if(!p.alive)return;let s=p.skills,t=nearestEnemy(p,650),lv;
if((lv=s.W01)&&cdReady(p,'W01',2.7,dt))areaDamage(p.x,p.y,78+10*lv,p.dmg*(1.05+.18*lv),p.id,{fx:'slash360',col:'#f0b18d'});
if((lv=s.W02)&&cdReady(p,'W02',6,dt))areaDamage(p.x,p.y,115+13*lv,p.dmg*(1.65+.25*lv),p.id,{fx:'quake',col:'#d4a576',slow:lv});
if((lv=s.W03)&&t&&cdReady(p,'W03',2.5,dt))proj(p,t.x,t.y,p.dmg*(1+.14*lv),{size:8,pierce:1+lv,col:'#dbe9c7',skill:'W03'});
if((lv=s.W04)&&t&&cdReady(p,'W04',7.5,dt)){let a=Math.atan2(t.y-p.y,t.x-p.x),ox=p.x,oy=p.y;p.x=Math.max(30,Math.min(WORLD.w-30,p.x+Math.cos(a)*(80+15*lv)));p.y=Math.max(30,Math.min(WORLD.h-30,p.y+Math.sin(a)*(80+15*lv)));p.shield+=p.max*(.06+.025*lv);lineDamage(ox,oy,p.x,p.y,30,p.dmg*(1+.2*lv),p.id,{fx:'charge',col:'#d9c7a5'})}
if((lv=s.W05)&&cdReady(p,'W05',10,dt)){for(let e of enemiesIn(p.x,p.y,150+20*lv))e.targetPlayer=p.id;p.damageReduce=Math.max(p.damageReduce,.12+.04*lv);p.cd._tauntEnd=2.5+.4*lv;addFx('taunt',p.x,p.y,{r:150+20*lv,col:'#e08b6e'})}if(p.cd._tauntEnd>0){p.cd._tauntEnd-=dt;if(p.cd._tauntEnd<=0)p.damageReduce=0}
if((lv=s.W08)&&cdReady(p,'W08',4.8,dt)){let count=2+Math.floor(lv/2);for(let i=0;i<count;i++){let a=i*Math.PI*2/count;proj(p,p.x+Math.cos(a)*200,p.y+Math.sin(a)*200,p.dmg*(.85+.12*lv),{size:9,pierce:1,returning:true,col:'#cfa36e',skill:'W08'})}}
if((lv=s.W09)&&t&&cdReady(p,'W09',6,dt)){damageEnemy(t,p.dmg*(1.15+.2*lv),p.id,{crit:false});let a=Math.atan2(p.y-t.y,p.x-t.x);t.x+=Math.cos(a)*(70+20*lv);t.y+=Math.sin(a)*(70+20*lv);addFx('chain',p.x,p.y,{r:Math.hypot(t.x-p.x,t.y-p.y),angle:Math.atan2(t.y-p.y,t.x-p.x),col:'#aaa58e'})}
if((lv=s.W12)&&cdReady(p,'W12',9,dt)){p.shield+=p.max*(.10+.04*lv);addFx('shield',p.x,p.y,{r:45,col:'#afc8c0'})}
if((lv=s.W13)&&cdReady(p,'W13',12,dt)){for(let a of Object.values(g.players)){a.atkBuff=1.08+.035*lv;a.atkBuffUntil=g.t+4+lv*.5}addFx('warcry',p.x,p.y,{r:180,col:'#e3a264'})}
if((lv=s.W14)&&cdReady(p,'W14',12,dt))addZone('guardian',g.n.x,g.n.y,130+15*lv,5+lv*.5,p.id,p.dmg*(.22+.04*lv),{col:'#91b76b'});
if((lv=s.W15)&&t&&cdReady(p,'W15',5.2,dt)){let mult=t.hp/t.max<.3?1.8:1;damageEnemy(t,p.dmg*(2.2+.35*lv)*mult,p.id,{crit:true});addFx('execute',t.x,t.y,{r:55,col:'#e06859'})}
if((lv=s.A03)&&t&&cdReady(p,'A03',7,dt))addZone('arrowrain',t.x,t.y,105+12*lv,3.5+.4*lv,p.id,p.dmg*(.35+.05*lv),{col:'#c9d99b'});
if((lv=s.A05)&&t&&cdReady(p,'A05',6.5,dt))proj(p,t.x,t.y,p.dmg*(2.3+.35*lv),{size:8,pierce:2,col:'#f1d28a',skill:'A05'});
if((lv=s.A09)&&cdReady(p,'A09',11,dt)){p.cd._rapid=2.2+.35*lv;addFx('rapid',p.x,p.y,{r:55,col:'#a8d8a0'})}if(p.cd._rapid>0)p.cd._rapid-=dt;
if((lv=s.A10)&&t&&cdReady(p,'A10',8,dt)){t.markedUntil=g.t+5+lv*.5;addFx('mark',t.x,t.y,{r:35,col:'#e9ca65'})}
if((lv=s.A11)&&t&&cdReady(p,'A11',2.8-.18*Math.min(lv,4),dt)){proj({...p,x:p.x+26,y:p.y-40},t.x,t.y,p.dmg*(.55+.12*lv),{size:4,col:'#a7d67b',skill:'A11'});addFx('falcon',p.x+26,p.y-40,{r:22,col:'#a7d67b'})}
if((lv=s.A12)&&cdReady(p,'A12',6.8,dt))addZone('trap',p.x+(Math.random()-.5)*80,p.y+(Math.random()-.5)*80,42+5*lv,12,p.id,p.dmg*(1+.18*lv),{col:'#9f875d',slow:lv,trigger:true});
if((lv=s.A13)&&t&&cdReady(p,'A13',5,dt))proj(p,t.x,t.y,p.dmg*(1.1+.18*lv),{size:11,pierce:4,returning:true,col:'#d9ebbc',skill:'A13'});
if((lv=s.A15)&&t&&cdReady(p,'A15',10,dt))addZone('storm',t.x,t.y,135+12*lv,4+.4*lv,p.id,p.dmg*(.42+.06*lv),{col:'#b9d6b0'});
if((lv=s.M01)&&t&&cdReady(p,'M01',2.8,dt))proj(p,t.x,t.y,p.dmg*(1.25+.16*lv),{size:9,explode:lv,col:'#e77b45',skill:'M01'});
if((lv=s.M02)&&t&&cdReady(p,'M02',3.6,dt))chainDamage(t,3+lv,p.dmg*(.9+.12*lv),p.id,{col:'#9bcfff'});
if((lv=s.M03)&&cdReady(p,'M03',6,dt))areaDamage(p.x,p.y,105+14*lv,p.dmg*(1.1+.18*lv),p.id,{fx:'iceburst',col:'#9ed4e6',slow:lv});
if((lv=s.M04)&&t&&cdReady(p,'M04',8,dt)){g.delayed.push({type:'meteor',x:t.x,y:t.y,time:.85,ownerId:p.id,dmg:p.dmg*(2.3+.35*lv),r:85+10*lv,lv});addFx('target',t.x,t.y,{r:85+10*lv,col:'#e47a4f',life:.85})}
if((lv=s.M05)&&t&&cdReady(p,'M05',1.8,dt)){let count=1+Math.ceil(lv/2);for(let i=0;i<count;i++){let a=g.t*2+i*Math.PI*2/count,op={...p,x:p.x+Math.cos(a)*55,y:p.y+Math.sin(a)*55};proj(op,t.x,t.y,p.dmg*(.45+.08*lv),{size:6,homing:1,col:'#9e90e5',skill:'M05'})}}
if((lv=s.M06)&&t&&cdReady(p,'M06',3.2,dt)){let count=2+lv;for(let i=0;i<count;i++)proj(p,t.x+(Math.random()-.5)*120,t.y+(Math.random()-.5)*120,p.dmg*(.48+.06*lv),{size:5,homing:1,col:'#b1a4ef',skill:'M06'})}
if((lv=s.M07)&&t&&cdReady(p,'M07',5.5,dt)){let a=Math.atan2(t.y-p.y,t.x-p.x);lineDamage(p.x,p.y,p.x+Math.cos(a)*650,p.y+Math.sin(a)*650,14+3*lv,p.dmg*(1.5+.22*lv),p.id,{fx:'beam',col:'#bcb0ff'})}
if((lv=s.M08)&&t&&cdReady(p,'M08',10,dt))addZone('blizzard',t.x,t.y,125+14*lv,5+.5*lv,p.id,p.dmg*(.28+.05*lv),{col:'#a9dfea',slow:lv});
if((lv=s.M09)&&t&&cdReady(p,'M09',8,dt)){let a=Math.atan2(t.y-g.n.y,t.x-g.n.x)+Math.PI/2;for(let i=-2;i<=2;i++)addZone('firewall',g.n.x+Math.cos(a)*i*(38+5*lv),g.n.y+Math.sin(a)*i*(38+5*lv),30,5+.4*lv,p.id,p.dmg*(.38+.07*lv),{col:'#e1713e'})}
if((lv=s.M10)&&t&&cdReady(p,'M10',7,dt)){let count=3+lv;for(let i=0;i<count;i++){let e=g.e[(Math.random()*g.e.length)|0];if(e)g.delayed.push({type:'lightning',x:e.x,y:e.y,time:.12*i,ownerId:p.id,dmg:p.dmg*(.75+.09*lv),r:32,lv})}}
if((lv=s.M11)&&t&&cdReady(p,'M11',11,dt))addZone('blackhole',t.x,t.y,115+12*lv,4+.4*lv,p.id,p.dmg*(.25+.04*lv),{col:'#8d6db5',pull:80+20*lv});
if((lv=s.M12)&&t&&cdReady(p,'M12',4.2,dt)){let count=1+Math.floor(lv/3);for(let i=0;i<count;i++)proj(p,t.x+(i-(count-1)/2)*30,t.y,p.dmg*(1.1+.15*lv),{size:9,pierce:3+lv,slow:lv,col:'#b6e7f2',skill:'M12'})}
if((lv=s.M13)&&cdReady(p,'M13',6.5,dt)){let count=1+Math.floor(lv/2);for(let i=0;i<count;i++)addZone('mine',p.x+(Math.random()-.5)*160,p.y+(Math.random()-.5)*160,35+5*lv,14,p.id,p.dmg*(1.4+.2*lv),{col:'#b29bdc',trigger:true})}
if((lv=s.M14)&&t&&cdReady(p,'M14',2.6-.14*Math.min(lv,4),dt)){let cols=['#ed8a52','#9fdcf0','#d8c6ff'],col=cols[(Math.random()*3)|0];proj({...p,x:p.x-30,y:p.y-36},t.x,t.y,p.dmg*(.6+.1*lv),{size:6,homing:1,col,skill:'M14'});addFx('elemental',p.x-30,p.y-36,{r:20,col})}
if((lv=s.M15)&&cdReady(p,'M15',12,dt))addZone('time',p.x,p.y,130+16*lv,5+.5*lv,p.id,0,{col:'#8fa8dc',slow:lv});
if((lv=s.P01)&&t&&cdReady(p,'P01',2.6,dt)){let targets=[...g.e].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y)).slice(0,1+Math.floor(lv/2));targets.forEach(e=>{damageEnemy(e,p.dmg*(1.05+.15*lv),p.id);addFx('holybolt',e.x,e.y,{r:35,col:'#f1e5a5'})})}
if((lv=s.P02)&&cdReady(p,'P02',10,dt)){for(let a of Object.values(g.players))if(Math.hypot(a.x-p.x,a.y-p.y)<250+20*lv)healPlayer(a,a.max*(.045+.018*lv));addFx('healwave',p.x,p.y,{r:250+20*lv,col:'#d9e8a1'})}
if((lv=s.P03)&&cdReady(p,'P03',9,dt))addZone('holyground',p.x,p.y,105+12*lv,5+.5*lv,p.id,p.dmg*(.25+.05*lv),{col:'#eadc83',heal:.012+.003*lv});
if((lv=s.P04)&&t&&cdReady(p,'P04',6.5,dt)){g.delayed.push({type:'judgment',x:t.x,y:t.y,time:.45,ownerId:p.id,dmg:p.dmg*(2+.3*lv),r:65+7*lv,lv});addFx('target',t.x,t.y,{r:65+7*lv,col:'#f0e39a',life:.45})}
if((lv=s.P05)&&cdReady(p,'P05',9,dt)){let arr=Object.values(g.players).filter(x=>x.alive).sort((a,b)=>a.hp/a.max-b.hp/b.max).slice(0,1+Math.floor(lv/2));arr.forEach(a=>{a.shield+=a.max*(.08+.025*lv);addFx('shield',a.x,a.y,{r:44,col:'#efe5a1'})})}
if((lv=s.P06)&&t&&cdReady(p,'P06',4.5,dt))chainDamage(t,3+lv,p.dmg*(.75+.11*lv),p.id,{col:'#f0e5a0',slow:lv});
if((lv=s.P07)&&t&&cdReady(p,'P07',2,dt)){let count=1+Math.ceil(lv/2);for(let i=0;i<count;i++){let a=g.t*2.4+i*Math.PI*2/count,op={...p,x:p.x+Math.cos(a)*52,y:p.y+Math.sin(a)*52};proj(op,t.x,t.y,p.dmg*(.42+.07*lv),{size:6,homing:1,col:'#efe4a4',skill:'P07'})}}
if((lv=s.P09)&&cdReady(p,'P09',13,dt)){for(let a of Object.values(g.players)){a.atkBuff=1.07+.03*lv;a.atkBuffUntil=g.t+5+lv*.4;a.speedBuff=1.05+.02*lv;a.speedBuffUntil=g.t+5+lv*.4}addFx('prayer',p.x,p.y,{r:190,col:'#f0df91'})}
if((lv=s.P10)&&t&&cdReady(p,'P10',4,dt)){let count=1+Math.floor(lv/3);for(let i=0;i<count;i++)proj(p,t.x+(i-(count-1)/2)*35,t.y,p.dmg*(1.1+.15*lv),{size:8,pierce:3+lv,col:'#f6e99b',skill:'P10'})}
if((lv=s.P11)&&cdReady(p,'P11',7,dt))areaDamage(p.x,p.y,100+12*lv,p.dmg*(.9+.14*lv),p.id,{fx:'holyfire',col:'#f1c978',burn:lv});
if((lv=s.P12))p.regen=Math.max(p.regen,.0025+.0015*lv);
if((lv=s.P13)&&t&&cdReady(p,'P13',8,dt)){t.markedUntil=g.t+5+lv*.7;addFx('judgemark',t.x,t.y,{r:42,col:'#f1d76f'})}
if((lv=s.P14)&&cdReady(p,'P14',14,dt))addZone('sanctuary',p.x,p.y,135+15*lv,5.5+.5*lv,p.id,0,{col:'#e8dfa0',heal:.010+.003*lv});
if((lv=s.P15)&&cdReady(p,'P15',10,dt))areaDamage(p.x,p.y,145+16*lv,p.dmg*(1.8+.25*lv),p.id,{fx:'holyburst',col:'#fff0a0'});
}
function doBasicAttack(p,t){let s=p.skills,rate=p.rate;if(s.W11&&p.hp/p.max<.55)rate*=Math.max(.5,1-(.07*s.W11));if(s.A09&&p.cd._rapid>0)rate*=Math.max(.42,1-.10*s.A09);let dmg=p.dmg;if(s.W11&&p.hp/p.max<.55)dmg*=1+.08*s.W11;if(p.cls==='warrior'){if(Math.hypot(t.x-p.x,t.y-p.y)<=p.rng+20){damageEnemy(t,dmg,p.id);addFx('slash',p.x,p.y,{r:p.rng,col:'#ead9c0',angle:Math.atan2(t.y-p.y,t.x-p.x)});p.hitCount++;if(s.W06&&Math.random()<.18+.06*s.W06){t.burn=Math.max(t.burn,dmg*(.08+.03*s.W06));t.burnUntil=g.t+4+s.W06*.5}if(s.W10&&p.hitCount>=Math.max(2,6-s.W10)){p.hitCount=0;areaDamage(p.x,p.y,90+8*s.W10,dmg*(.65+.12*s.W10),p.id,{fx:'crush',col:'#cfb891'})}}}else{let m=basicMods(p),count=p.cls==='archer'?1+(s.A01||0):1;for(let i=0;i<count;i++)proj(p,t.x+(i-(count-1)/2)*18,t.y,dmg*(i?0.7:1),{pierce:m.pierce,poison:m.poison,explode:m.explode,slow:m.slow,ricochet:m.ricochet,col:C[p.cls].col,skill:'basic'})}p.at=rate}
function updateZones(dt){for(let i=g.zones.length-1;i>=0;i--){let z=g.zones[i];z.life-=dt;z.tick-=dt;if(z.type==='blackhole'){for(let e of enemiesIn(z.x,z.y,z.r)){let a=Math.atan2(z.y-e.y,z.x-e.x);e.x+=Math.cos(a)*z.pull*dt;e.y+=Math.sin(a)*z.pull*dt}}if(z.tick<=0){z.tick=.38;if(z.trigger){let hit=enemiesIn(z.x,z.y,z.r);if(hit.length){hit.forEach(e=>damageEnemy(e,z.dmg,z.ownerId,{slow:z.slow}));addFx(z.type==='mine'?'arcaneexplode':'trapburst',z.x,z.y,{r:z.r*1.5,col:z.col});z.life=0}}else{if(z.dmg>0)enemiesIn(z.x,z.y,z.r).forEach(e=>damageEnemy(e,z.dmg,z.ownerId,{crit:false,slow:z.slow,burn:z.type==='firewall'?1:0}));if(z.slow>0)enemiesIn(z.x,z.y,z.r).forEach(e=>{e.slow=Math.min(e.slow,.75-.04*z.slow);e.slowUntil=g.t+.8});if(z.heal>0)for(let p of Object.values(g.players))if(Math.hypot(p.x-z.x,p.y-z.y)<=z.r)healPlayer(p,p.max*z.heal);if(z.type==='sanctuary')for(let p of Object.values(g.players))if(Math.hypot(p.x-z.x,p.y-z.y)<=z.r)p.damageReduce=Math.max(p.damageReduce,.18)}}if(z.life<=0)g.zones.splice(i,1)}}
function updateDelayed(dt){for(let i=g.delayed.length-1;i>=0;i--){let d=g.delayed[i];d.time-=dt;if(d.time<=0){if(d.type==='meteor')areaDamage(d.x,d.y,d.r,d.dmg,d.ownerId,{fx:'meteor',col:'#e77748',burn:d.lv});else if(d.type==='lightning')areaDamage(d.x,d.y,d.r,d.dmg,d.ownerId,{fx:'lightningStrike',col:'#a7d7ff'});else if(d.type==='judgment')areaDamage(d.x,d.y,d.r,d.dmg,d.ownerId,{fx:'judgment',col:'#f6e58f'});g.delayed.splice(i,1)}}}
function updateProjectiles(dt){for(let i=g.q.length-1;i>=0;i--){let q=g.q[i],owner=playerById(q.ownerId);if(q.homing){let e=nearestEnemy(owner||localPlayer(),500);if(e){let a=Math.atan2(e.y-q.y,e.x-q.x),sp=Math.hypot(q.vx,q.vy);q.vx=q.vx*.9+Math.cos(a)*sp*.1;q.vy=q.vy*.9+Math.sin(a)*sp*.1}}if(q.returning&&!q.returned&&q.life<.75&&owner){let a=Math.atan2(owner.y-q.y,owner.x-q.x),sp=Math.hypot(q.vx,q.vy);q.vx=Math.cos(a)*sp;q.vy=Math.sin(a)*sp;q.returned=true}q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0||q.x<0||q.y<0||q.x>WORLD.w||q.y>WORLD.h){g.q.splice(i,1);continue}let removed=false;for(let e of g.e){if(e.dead||q.hitIds.includes(e.id))continue;if((q.x-e.x)**2+(q.y-e.y)**2<(e.r+q.size+4)**2){q.hitIds.push(e.id);damageEnemy(e,q.d,q.ownerId,{poison:q.poison,slow:q.slow});if(q.explode)areaDamage(e.x,e.y,38+8*q.explode,q.d*(.25+.06*q.explode),q.ownerId,{fx:'explosion',col:'#e7804e',burn:q.skill==='M01'?q.explode:0});if(q.ricochet>0){let ownerP=owner||localPlayer(),n=nearestEnemy({...ownerP,x:e.x,y:e.y},230);if(n&&n.id!==e.id)proj({...ownerP,x:e.x,y:e.y},n.x,n.y,q.d*.65,{ricochet:q.ricochet-1,col:q.col,size:q.size})}if(q.pierce>0)q.pierce--;else{g.q.splice(i,1);removed=true}break}}if(removed)continue}}
function updateStatuses(dt){for(let e of g.e){if(e.dead)continue;if(e.slowUntil<=g.t)e.slow=1;e.dotTick-=dt;if(e.dotTick<=0){e.dotTick=.5;let dot=0;if(e.poisonUntil>g.t)dot+=e.poison*.5;if(e.burnUntil>g.t)dot+=e.burn*.5;if(dot>0){e.hp-=dot;addText(e.x,e.y-e.r,dot,'dot',false);if(e.hp<=0)killEnemy(e,localPlayer()?.id)}}}}
function updateEnemies(dt){for(let e of g.e){if(e.dead)continue;e.anim+=dt*7;let target=null;if(e.targetPlayer&&playerById(e.targetPlayer)?.alive)target=playerById(e.targetPlayer);if(!target){let best=260,chosen=null;for(let p of Object.values(g.players)){if(!p.alive)continue;let d=Math.hypot(p.x-e.x,p.y-e.y);if(d<best){best=d;chosen=p}}target=chosen||g.n}let a=Math.atan2(target.y-e.y,target.x-e.x),ds=e.spd*(e.slow||1)*dt;e.x+=Math.cos(a)*ds;e.y+=Math.sin(a)*ds;e.cd-=dt;if(Math.hypot(target.x-e.x,target.y-e.y)<e.r+(target===g.n?48:24)&&e.cd<=0){if(target===g.n)damageNexus(e.dmg);else damagePlayer(target,e.dmg);e.cd=e.boss?.7:1.05}}g.e=g.e.filter(e=>!e.dead)}
function updateGems(dt){let alive=Object.values(g.players).filter(p=>p.alive);for(let i=g.gem.length-1;i>=0;i--){let z=g.gem[i],near=null,bd=99999;for(let p of alive){let d=Math.hypot(p.x-z.x,p.y-z.y);if(d<bd){bd=d;near=p}}z.spin+=dt*4;if(near&&bd<near.pickup){let a=Math.atan2(near.y-z.y,near.x-z.x);z.x+=Math.cos(a)*380*dt;z.y+=Math.sin(a)*380*dt}if(near&&bd<24){gainPartyXp(z.v);g.gem.splice(i,1)}}}
function updatePlayers(dt){for(let p of Object.values(g.players)){if(!p.alive)continue;let input=NET.mode==='host'?netInputFor(p.id):p.id===g.localId?{up:keys.KeyW,down:keys.KeyS,left:keys.KeyA,right:keys.KeyD}:{};let dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0),l=Math.hypot(dx,dy)||1;if(dx||dy){p.face=dx<0?-1:dx>0?1:p.face;p.walk+=dt*10}let spd=p.spd*(p.speedBuffUntil>g.t?p.speedBuff:1);p.x=Math.max(25,Math.min(WORLD.w-25,p.x+dx/l*spd*dt));p.y=Math.max(30,Math.min(WORLD.h-25,p.y+dy/l*spd*dt));p.tx=p.x;p.ty=p.y;p.hp=Math.min(p.max,p.hp+p.max*p.regen*dt);p.guardianCd=Math.max(0,p.guardianCd-dt);if(p.atkBuffUntil<=g.t)p.atkBuff=1;if(p.speedBuffUntil<=g.t)p.speedBuff=1;p.at-=dt;let t=nearestEnemy(p);if(t&&p.at<=0)doBasicAttack(p,t);runSkills(p,dt)}}
function updateNexus(dt){let n=g.n;n.hp=Math.min(n.max,n.hp+n.max*n.regen*dt);if(n.turret>0){n.cd-=dt;if(n.cd<=0){let p=localPlayer(),e=strongestEnemy(700,{...p,x:n.x,y:n.y});if(e){let fake={...p,id:p.id,x:n.x,y:n.y,cls:'priest'};proj(fake,e.x,e.y,18+n.turret*11,{source:'nexus',col:'#b6e47b',size:6})}n.cd=Math.max(.18,.8-n.turret*.08)}}}
function updateFx(dt){for(let i=g.fx.length-1;i>=0;i--){let f=g.fx[i];if(f.type==='particle'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.9;f.vy*=.9}f.life-=dt;if(f.life<=0)g.fx.splice(i,1)}for(let i=g.text.length-1;i>=0;i--){let t=g.text[i];t.y+=t.vy*dt;t.life-=dt;if(t.life<=0)g.text.splice(i,1)}g.shake*=.86}
function updateHost(dt){if(state!=='play'||!g)return;g.t+=dt;let f=DF[diff],ps=PARTY[partyCount()]||PARTY[4];g.spawn-=dt;if(g.spawn<=0&&!g.boss&&g.e.length<(NET.mode==='host'?230:320)){spawn();g.spawn=Math.max(.10,.74/(f[2]*ps[1]*(1+g.stage*.2)+g.t/180))}if(g.t>75&&!g.boss)spawn(true);updatePlayers(dt);updateEnemies(dt);updateProjectiles(dt);updateZones(dt);updateDelayed(dt);updateStatuses(dt);updateGems(dt);updateNexus(dt);updateFx(dt);if(NET.mode==='host'){g.snapCd-=dt;if(g.snapCd<=0){g.snapCd=.125;netSnapshotBroadcast(makeNetState())}}hud()}
function updateClient(dt){if(state!=='play'||!g)return;g.t+=dt;netSendInput(dt);let lp=localPlayer();if(lp&&lp.alive){let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0),l=Math.hypot(dx,dy)||1;if(dx||dy){lp.face=dx<0?-1:dx>0?1:lp.face;lp.walk+=dt*10}lp.x=Math.max(25,Math.min(WORLD.w-25,lp.x+dx/l*lp.spd*dt));lp.y=Math.max(30,Math.min(WORLD.h-25,lp.y+dy/l*lp.spd*dt))}for(let p of Object.values(g.players)){if(p.id===g.localId){p.x+=(p.tx-p.x)*Math.min(1,dt*3);p.y+=(p.ty-p.y)*Math.min(1,dt*3)}else{p.x+=(p.tx-p.x)*Math.min(1,dt*9);p.y+=(p.ty-p.y)*Math.min(1,dt*9);p.walk+=dt*7}}for(let e of g.e){e.x+=(e.tx-e.x)*Math.min(1,dt*8);e.y+=(e.ty-e.y)*Math.min(1,dt*8);e.anim+=dt*7}for(let q of g.q){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}g.q=g.q.filter(q=>q.life>0);updateFx(dt);hud()}
function update(dt){dt=Math.min(dt,.033);if(NET.mode==='client')updateClient(dt);else updateHost(dt)}
function makeNetState(){return{t:g.t,stage:g.stage,kills:g.kills,boss:g.boss,diff,n:{x:g.n.x,y:g.n.y,hp:g.n.hp,max:g.n.max,lv:g.n.lv,core:g.n.core,next:g.n.next,turret:g.n.turret,regen:g.n.regen},players:Object.values(g.players).map(p=>({id:p.id,cls:p.cls,x:p.x,y:p.y,hp:p.hp,max:p.max,l:p.l,xp:p.xp,nxp:p.nxp,crit:p.crit,skills:p.skills,face:p.face,alive:p.alive,shield:p.shield,spd:p.spd,dmg:p.dmg})),e:g.e.slice(0,240).map(e=>({id:e.id,x:e.x,y:e.y,r:e.r,hp:e.hp,max:e.max,type:e.type,boss:e.boss,anim:e.anim})),q:g.q.slice(0,180).map(q=>({x:q.x,y:q.y,vx:q.vx,vy:q.vy,life:q.life,col:q.col,size:q.size,source:q.source})),gem:g.gem.slice(0,220).map(z=>({x:z.x,y:z.y,v:z.v,spin:z.spin})),zones:g.zones.slice(0,30).map(z=>({type:z.type,x:z.x,y:z.y,r:z.r,life:z.life,max:z.max,col:z.col}))}}
function applyNetSnapshot(s,initial=false){if(!g)return;if(s.diff)diff=s.diff;g.t=s.t;g.stage=s.stage;g.kills=s.kills;g.boss=s.boss;Object.assign(g.n,s.n);let existing=g.players||{};for(let d of s.players){let p=existing[d.id]||makePlayer(d.id,d.cls,d.x,d.y),ox=p.x,oy=p.y;Object.assign(p,d);p.tx=d.x;p.ty=d.y;if(initial){p.x=d.x;p.y=d.y}else{p.x=ox;p.y=oy}existing[d.id]=p}for(let id of Object.keys(existing))if(!s.players.some(p=>p.id===id))delete existing[id];g.players=existing;let em=new Map(g.e.map(e=>[e.id,e])),arr=[];for(let d of s.e){let e=em.get(d.id)||{...d,x:d.x,y:d.y,tx:d.x,ty:d.y};e.tx=d.x;e.ty=d.y;e.r=d.r;e.hp=d.hp;e.max=d.max;e.type=d.type;e.boss=d.boss;e.anim=d.anim;arr.push(e)}g.e=arr;g.q=s.q.map(q=>({...q}));g.gem=s.gem.map(z=>({...z}));g.zones=s.zones.map(z=>({...z}));$('bosshud').classList.toggle('hidden',!g.boss);if(g.boss)$('bname').textContent=ST[g.stage].boss}
function applyNetEvent(ev){if(!g||!ev)return;if(ev.k==='fx')g.fx.push({...ev.fx});else if(ev.k==='text')g.text.push({...ev.t})}
function hud(){if(!g)return;let p=localPlayer(),n=g.n;if(!p)return;$('stage').textContent='STAGE '+(g.stage+1)+' // '+ST[g.stage].name;$('time').textContent=String((g.t/60)|0).padStart(2,'0')+':'+String(g.t%60|0).padStart(2,'0')+' · '+diff;$('enemyInfo').textContent='HOSTILES '+g.e.length+' · MAP 2600×1800';$('ntext').textContent=Math.max(0,n.hp|0)+' / '+(n.max|0);$('nbar').style.width=Math.max(0,n.hp/n.max*100)+'%';$('corebar').style.width=Math.min(100,n.core/n.next*100)+'%';$('core').textContent='CORE LV.'+n.lv+' · '+(n.core|0)+'/'+(n.next|0)+' · TURRET '+n.turret;$('pname').textContent=C[p.cls].n.toUpperCase();$('ptext').textContent=Math.max(0,p.hp|0)+' / '+(p.max|0)+(p.shield>0?' +SH '+(p.shield|0):'');$('pbar').style.width=Math.max(0,p.hp/p.max*100)+'%';$('xbar').style.width=Math.max(0,p.xp/p.nxp*100)+'%';$('lvl').textContent='LEVEL '+p.l+' · ATK '+(p.dmg|0)+' · CRIT '+Math.round(p.crit*100)+'%';$('runData').textContent=g.kills+' KILLS';$('netData').textContent=NET.mode==='solo'?'SOLO':(NET.mode==='host'?'HOST · '+partyCount()+'P':'CLIENT · '+partyCount()+'P');let tags=$('skillTags');tags.innerHTML='';Object.entries(p.skills).slice(0,7).forEach(([id,v])=>{let s=document.createElement('span');s.className='skillTag';s.textContent=(skillDef(p.cls,id)?.n||id)+' '+v;tags.appendChild(s)});let b=g.e.find(x=>x.boss);if(b){$('btext').textContent=Math.max(0,b.hp|0)+' / '+(b.max|0);$('bbar').style.width=Math.max(0,b.hp/b.max*100)+'%'}}
function endGame(reason,victory=false,fromNet=false){if(state==='ended')return;state='ended';$('levelModal').classList.add('hidden');$('chestModal').classList.add('hidden');$('endModal').classList.remove('hidden');$('endEyebrow').textContent=victory?'RUN COMPLETE':'RUN TERMINATED';$('endTitle').textContent=victory?'VICTORY':'GAME OVER';$('endText').textContent=reason;if(NET.mode==='host'&&!fromNet)netEndBroadcast(reason,victory)}
function resetToMenu(){netClose();g=null;state='menu';choiceOwner=null;$('endModal').classList.add('hidden');$('levelModal').classList.add('hidden');$('chestModal').classList.add('hidden');$('hud').classList.add('hidden');$('menu').classList.remove('hidden');$('bosshud').classList.add('hidden');netSetMode('solo');menu();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H)} $('returnMenuBtn').onclick=resetToMenu;
window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyB'&&g&&state==='play'&&NET.mode!=='client'&&!g.boss)spawn(true)});window.addEventListener('keyup',e=>keys[e.code]=false);menu();
