import puppeteer from 'puppeteer-core';

const base=process.env.NEXUS_QA_URL||'http://127.0.0.1:4173/';
const expectedBuild=process.env.NEXUS_EXPECTED_BUILD||'0.21';
const chrome=process.env.CHROME_BIN||'/usr/bin/google-chrome';
const browser=await puppeteer.launch({headless:true,executablePath:chrome,protocolTimeout:30000,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const fail=(msg,detail='')=>{throw new Error(`${msg}${detail?` :: ${detail}`:''}`)};
const mark=s=>console.log(`QA STEP :: ${s}`);

async function openPage(label,mobile=false){
  mark(`${label}:open`);const page=await browser.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));
  page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(`console: ${m.text()}`)});
  page.on('response',r=>{if(r.status()<400)return;try{if(new URL(r.url()).pathname.endsWith('/favicon.ico'))return}catch{}errors.push(`http ${r.status()}: ${r.url()}`)});
  if(mobile){await page.setUserAgent('Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1');await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:2})}
  else await page.setViewport({width:1280,height:720,deviceScaleFactor:1});
  await page.goto(base,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(build=>window.NEXUS_RUNTIME_CHECK?.build===build,{timeout:12000},expectedBuild);const qa=await page.evaluate(()=>window.NEXUS_RUNTIME_CHECK);if(!qa.ok)fail(`${label}:runtime QA`,JSON.stringify(qa.failed));mark(`${label}:ready`);return {page,errors};
}
async function startSolo(page,label){mark(`${label}:start-solo`);await page.evaluate(()=>document.getElementById('start')?.click());await page.waitForFunction(()=>eval("state==='play'&&!!g&&!!localPlayer()"),{timeout:5000});await page.evaluate(()=>eval("localPlayer().at=999"))}
async function population(page){return page.evaluate(()=>eval(`(()=>{const cam=g?.cam||{x:0,y:0},enemies=(g?.e||[]).filter(e=>!e.dead&&!e.boss),visible=enemies.filter(e=>e.x>=cam.x-40&&e.x<=cam.x+W+40&&e.y>=cam.y-40&&e.y<=cam.y+H+40);return {hostiles:enemies.length,visible:visible.length,nextEnemyId:g?.nextEnemyId||0,time:g?.t||0,ids:enemies.map(e=>e.id).slice(0,60),graded:enemies.filter(e=>!!e.grade&&!!e.variantRole).length,meta:enemies.slice(0,60).map(e=>({id:e.id,grade:e.grade,role:e.variantRole}))}})()`))}
async function takeHostMessages(host){return host.evaluate(()=>{const a=window.__qaHostOut||[];window.__qaHostOut=[];return a})}
async function takeClientMessages(client){return client.evaluate(()=>{const a=window.__qaClientOut||[];window.__qaClientOut=[];return a})}
async function deliverToClient(client,msgs){if(!msgs.length)return;await client.evaluate(ms=>{window.__qaMsgs=ms;eval(`for(const m of window.__qaMsgs)netClientMessage(m)`);delete window.__qaMsgs},msgs)}
async function deliverToHost(host,msgs){if(!msgs.length)return;await host.evaluate(ms=>{window.__qaMsgs=ms;eval(`const c=NET.conns.get('qa-client');for(const m of window.__qaMsgs)netHostMessage(c,m)`);delete window.__qaMsgs},msgs)}
async function stepHost(host,seconds){await host.evaluate(sec=>{window.__qaSecs=sec;eval(`for(let i=0,n=Math.ceil(window.__qaSecs*60);i<n;i++)updateHost(1/60)`);delete window.__qaSecs},seconds)}

try{
  const soloPack=await openPage('solo'),solo=soloPack.page;const label=await solo.evaluate(()=>document.querySelector('.brandCorner')?.textContent||'');if(!label.includes(expectedBuild))fail('wrong build label',label);await startSolo(solo,'solo');await solo.waitForFunction(()=>eval(`(()=>{const c=g.cam||{x:0,y:0},es=g.e.filter(e=>!e.dead&&!e.boss),v=es.filter(e=>e.x>=c.x-40&&e.x<=c.x+W+40&&e.y>=c.y-40&&e.y<=c.y+H+40).length;return es.length>=10&&v>=4&&g.nextEnemyId>=11})()`),{timeout:9000});const soloPop=await population(solo);if(soloPop.hostiles<10||soloPop.visible<4||soloPop.graded!==soloPop.hostiles)fail('solo swarm/grade failed',JSON.stringify(soloPop));mark(`solo:PASS ${soloPop.hostiles}/${soloPop.visible} graded=${soloPop.graded}`);
  mark('solo:grade-xp');const xpCheck=await solo.evaluate(()=>eval(`(()=>{const e=g.e.find(x=>!x.dead&&!x.boss);if(!e)return null;e.grade='legendary';e.gradeColor='#ffbd55';e.gradeXp=3;const before=g.gem.length;killEnemy(e,'p1');return {values:g.gem.slice(before).map(x=>x.v),before,after:g.gem.length}})()`));if(!xpCheck||!xpCheck.values.some(v=>v>=18))fail('grade XP multiplier failed',JSON.stringify(xpCheck));mark(`solo:grade-xp PASS ${xpCheck.values.join(',')}`);if(soloPack.errors.length)fail('solo browser errors',soloPack.errors.join(' | '));await solo.close();

  const hostPack=await openPage('multi-host'),clientPack=await openPage('multi-client'),host=hostPack.page,client=clientPack.page;
  mark('multi:initialize-host');await host.evaluate(()=>eval(`(()=>{NET.mode='host';NET.ready=true;NET.localId='p1';NET.lobby={p1:{id:'p1',cls:'warrior',name:'HOST'},p2:{id:'p2',cls:'warrior',name:'PLAYER 2'}};NET.inputs={p2:{}};window.__qaHostOut=[];const c={open:true,playerId:'p2',peer:'qa-client',send:m=>window.__qaHostOut.push(JSON.parse(JSON.stringify(m)))};NET.conns=new Map([['qa-client',c]]);startRun()})()`));await host.waitForFunction(()=>eval("state==='play'&&Object.keys(g.players).length===2"),{timeout:5000});const startMsgs=await takeHostMessages(host),startMsg=startMsgs.find(m=>m.t==='start');if(!startMsg)fail('host did not emit start');
  mark('multi:initialize-client');await client.evaluate(m=>{window.__qaStart=m;eval(`NET.mode='client';NET.ready=true;NET.localId='p2';NET.lobby={p1:{id:'p1',cls:'warrior',name:'HOST'},p2:{id:'p2',cls:'warrior',name:'PLAYER 2'}};window.__qaClientOut=[];NET.hostConn={open:true,send:x=>window.__qaClientOut.push(JSON.parse(JSON.stringify(x)))};netClientMessage(window.__qaStart)`);delete window.__qaStart},startMsg);await client.waitForFunction(()=>eval("state==='play'&&g?.localId==='p2'&&Object.keys(g.players).length===2"),{timeout:5000});await host.evaluate(()=>eval("Object.values(g.players).forEach(p=>p.at=999)"));

  mark('multi:enemy-snapshot-sync');await stepHost(host,4.0);await deliverToClient(client,await takeHostMessages(host));const hostPop=await population(host),clientPop=await population(client),overlap=hostPop.ids.filter(id=>clientPop.ids.includes(id)).length;if(hostPop.hostiles<10||clientPop.hostiles<9||overlap<9)fail('enemy snapshot sync failed',JSON.stringify({hostPop,clientPop,overlap}));const cm=new Map(clientPop.meta.map(x=>[x.id,x])),gradeMatches=hostPop.meta.filter(x=>cm.has(x.id)&&cm.get(x.id).grade===x.grade&&cm.get(x.id).role===x.role).length;if(gradeMatches<9)fail('grade metadata sync failed',JSON.stringify({gradeMatches,host:hostPop.meta,client:clientPop.meta}));mark(`multi:enemy PASS ${hostPop.hostiles}/${clientPop.hostiles} overlap=${overlap} grades=${gradeMatches}`);

  mark('multi:remote-input');const beforeMove=await host.evaluate(()=>eval('g.players.p2.x'));await client.evaluate(()=>eval("keys.KeyD=true;NET.lastInputSend=0;netSendInput(.1)"));await deliverToHost(host,(await takeClientMessages(client)).filter(m=>m.t==='input'));await stepHost(host,.55);await client.evaluate(()=>eval("keys.KeyD=false;NET.lastInputSend=0;netSendInput(.1)"));await deliverToHost(host,(await takeClientMessages(client)).filter(m=>m.t==='input'));const afterMove=await host.evaluate(()=>eval('g.players.p2.x'));if(afterMove<=beforeMove+15)fail('remote input failed',`${beforeMove}->${afterMove}`);mark(`multi:input PASS ${beforeMove.toFixed(1)}->${afterMove.toFixed(1)}`);

  mark('multi:boss-reward');await host.evaluate(()=>eval(`(()=>{g.e=[];g.boss=false;g.stage=0;for(const p of Object.values(g.players)){p.skills={W01:1};p.advSkills={};p.pendingLevel=false}netSnapshotBroadcast(makeNetState())})()`));await deliverToClient(client,await takeHostMessages(host));await client.waitForFunction(()=>eval("localPlayer().skills.W01===1"),{timeout:3000});await host.evaluate(()=>eval('openChest()'));await deliverToClient(client,await takeHostMessages(host));await host.waitForFunction(()=>eval("state==='chest'&&g.players.p1.skills.W01===2&&g.players.p2.skills.W01===2"),{timeout:3000});await client.waitForFunction(()=>eval("state==='chest'&&localPlayer().skills.W01===2&&!document.getElementById('chestModal').classList.contains('hidden')"),{timeout:3000});const rewardCheck=await Promise.all([host.evaluate(()=>eval("({p1:g.players.p1.skills.W01,p2:g.players.p2.skills.W01,ids:Object.keys(g._v19ChestGranted.rewards).sort().join(',')})")),client.evaluate(()=>eval("({p2:localPlayer().skills.W01,shown:!document.getElementById('chestModal').classList.contains('hidden')})"))]);if(rewardCheck[0].p1!==2||rewardCheck[0].p2!==2||rewardCheck[0].ids!=='p1,p2'||rewardCheck[1].p2!==2||!rewardCheck[1].shown)fail('party reward failed',JSON.stringify(rewardCheck));mark('multi:reward PASS both players');await host.evaluate(()=>document.getElementById('rewardBtn').click());await deliverToClient(client,await takeHostMessages(host));await client.waitForFunction(()=>eval("state==='play'&&g.stage===1"),{timeout:3000});

  mark('multi:dash-sync');await client.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',key:' ',bubbles:true,cancelable:true})));let cmsgs=await takeClientMessages(client),dashMsg=[...cmsgs].reverse().find(m=>m.t==='smoothDash12');if(!dashMsg)fail('client did not emit smoothDash12',JSON.stringify(cmsgs));await deliverToHost(host,[dashMsg]);await host.waitForFunction(()=>eval("(g.players.p2.dashReadyAt||0)>g.t+1"),{timeout:3000});await stepHost(host,.25);await deliverToClient(client,await takeHostMessages(host));let dashA=await Promise.all([host.evaluate(()=>eval("Math.max(0,g.players.p2.dashReadyAt-g.t)")),client.evaluate(()=>eval("Math.max(0,(localPlayer().dashReadyAt||0)-g.t)"))]);if(Math.abs(dashA[0]-dashA[1])>.30)fail('dash clock mismatch A',JSON.stringify(dashA));await stepHost(host,.70);await deliverToClient(client,await takeHostMessages(host));let dashB=await Promise.all([host.evaluate(()=>eval("Math.max(0,g.players.p2.dashReadyAt-g.t)")),client.evaluate(()=>eval("Math.max(0,(localPlayer().dashReadyAt||0)-g.t)"))]);if(Math.abs(dashB[0]-dashB[1])>.30||dashB[0]>=dashA[0]-.35||dashB[1]>=dashA[1]-.35)fail('dash clock mismatch B',JSON.stringify({dashA,dashB}));mark(`multi:dash PASS ${dashA.map(x=>x.toFixed(2)).join('/')} -> ${dashB.map(x=>x.toFixed(2)).join('/')}`);
  if(hostPack.errors.length)fail('host browser errors',hostPack.errors.join(' | '));if(clientPack.errors.length)fail('client browser errors',clientPack.errors.join(' | '));await host.close();await client.close();

  const mobilePack=await openPage('mobile',true),mobile=mobilePack.page;await startSolo(mobile,'mobile');await mobile.waitForFunction(()=>{const j=document.getElementById('joystick'),r=j?.getBoundingClientRect();return !!j&&r.width>0&&r.height>0},{timeout:5000});await mobile.waitForFunction(()=>eval("g.e.filter(e=>!e.dead&&!e.boss).length>=6"),{timeout:8000});const mobileState=await mobile.evaluate(()=>{const j=document.getElementById('joystick'),d=document.getElementById('raidDashBtn'),r=j?.getBoundingClientRect(),es=g.e.filter(e=>!e.dead&&!e.boss);return {mobile:document.documentElement.classList.contains('mobile-build'),joystick:!!j&&r.width>0&&r.height>0,dash:!!d,hostiles:es.length,graded:es.filter(e=>!!e.grade).length}});if(!mobileState.mobile||!mobileState.joystick||!mobileState.dash||mobileState.hostiles<6||mobileState.graded!==mobileState.hostiles)fail('mobile failed',JSON.stringify(mobileState));if(mobilePack.errors.length)fail('mobile browser errors',mobilePack.errors.join(' | '));await mobile.close();

  console.log(`PASS browser:build-${expectedBuild} :: ${base}`);console.log(`PASS browser:solo-swarm :: ${soloPop.hostiles}/${soloPop.visible}`);console.log(`PASS browser:grade-xp :: ${xpCheck.values.join(',')}`);console.log(`PASS browser:2p-enemy-grade-sync :: ${hostPop.hostiles}/${clientPop.hostiles} overlap=${overlap} grades=${gradeMatches}`);console.log('PASS browser:2p-party-boss-rewards');console.log('PASS browser:2p-dash-clock-sync');console.log('PASS browser:2p-remote-input');console.log(`PASS browser:mobile-swarm :: ${mobileState.hostiles}`);console.log('8/8 focused browser checks passed');
} finally {await browser.close().catch(()=>{})}
