import fs from 'node:fs';
import path from 'node:path';
const root=process.argv[2]||'nexus-survival',read=f=>fs.readFileSync(path.join(root,f),'utf8'),exists=f=>fs.existsSync(path.join(root,f));
const results=[],check=(name,ok,detail='')=>results.push({name,ok:!!ok,detail});
const required=['index.html','manifest.webmanifest','game-core.js','game-multi.js','game-render.js','game-raid-v11.js','game-mobile-v12.js','game-progression-v13.js','game-spawn-v18.js','game-multiplayer-v19.js','game-visual-v20.js','game-swarm-v21.js','game-power-v22.js','game-buffs-v23.js','game-expansion-v24.js','game-expansion-fix-v24.js','game-boss-tiers-v24.js','game-buildcraft-v25.js','game-buildcraft-fix-v25.js','game-polish-v26.js','game-motion-v27.js','game-party-v28.js','game-verify-v26.js','game-verify-v27.js','game-verify-v28.js','qa-v27.mjs','qa-v28.mjs'];
for(const f of required)check(`file:${f}`,exists(f));
const index=read('index.html'),manifest=JSON.parse(read('manifest.webmanifest')),progression=read('game-progression-v13.js'),spawn=read('game-spawn-v18.js'),multi=read('game-multiplayer-v19.js'),visual=read('game-visual-v20.js'),swarm=read('game-swarm-v21.js'),power=read('game-power-v22.js'),buffs=read('game-buffs-v23.js'),exp=read('game-expansion-v24.js'),boss=read('game-boss-tiers-v24.js'),buildcraft=read('game-buildcraft-v25.js'),polish=read('game-polish-v26.js'),motion=read('game-motion-v27.js'),party=read('game-party-v28.js'),verify26=read('game-verify-v26.js'),verify27=read('game-verify-v27.js'),verify28=read('game-verify-v28.js'),mobile=read('game-mobile-v12.js');
check('build:0.28',index.includes('BUILD 0.28')&&index.includes('PROTOCOL // 28')&&index.includes('FIELD MANUAL / 28'));
check('cache:v28',index.includes('game-party-v28.js?v=28')&&index.includes('game-verify-v28.js?v=28'));
check('verify:last-script',index.lastIndexOf('game-verify-v28.js')>index.lastIndexOf('game-party-v28.js')&&index.lastIndexOf('game-verify-v28.js')>index.lastIndexOf('game-verify-v27.js'));
check('mobile:portrait',manifest.orientation==='portrait'&&index.includes('screen-orientation'));
check('classes:7',['C.necromancer','C.rogue','C.gunslinger'].every(x=>exp.includes(x))&&index.includes('7 BASE CLASSES'));
check('mobile:7-dashes',['warrior','archer','mage','priest','necromancer','rogue','gunslinger'].every(x=>mobile.includes(`${x}:{name:`)));
check('progression:50',progression.includes('for(let i=0;i<50;i++)')&&progression.includes('window.NEXUS_MAX_STAGE=50'));
check('spawn:watchdog',spawn.includes('minPopulation')&&spawn.includes('spawn(false)'));
check('multi:rewards-dash',multi.includes('partyBossRewards:true')&&multi.includes('dashClockSync:true'));
check('visual:monster-boss',visual.includes('monsterSilhouettes:25')&&visual.includes('bossSilhouettes:15'));
check('swarm:2x-grades',swarm.includes('spawnMultiplier:2')&&['common','uncommon','rare','epic','legendary'].every(x=>swarm.includes(`${x}:{name:`))&&swarm.includes('gradeXp'));
check('power:stage-curve',power.includes('const START=1.04')&&power.includes('const CAP=1.24'));
check('buff:right-hud',buffs.includes('rightHud:true')&&buffs.includes('hostClockSync:true'));
check('exp:5p',exp.includes('maxPlayers:5')&&exp.includes('PARTY[5]'));
check('exp:boss-adds',exp.includes('g._bossAddCd')&&exp.includes('bossAdds:true'));
check('boss:hierarchy',boss.includes('midStages:[5,15,25,35,45]')&&boss.includes('majorStages:[10,20,30,40,50]')&&boss.includes('midPatterns:4')&&boss.includes('majorPatterns:5'));
check('buildcraft:max10',buildcraft.includes('BASE_MAX=10,ADV_MAX=10'));
check('buildcraft:slots3',buildcraft.includes('ADV_SLOTS=3'));
check('buildcraft:273-runtime-counts',buildcraft.includes('baseSkills:Object.values(SK||{})')&&buildcraft.includes('advancedSkills:Object.values(ADV)'));
check('buildcraft:synergy',buildcraft.includes('const SYNERGIES=[]')&&buildcraft.includes('allSkillsHaveCombo:true')&&buildcraft.includes('SYNERGY'));
check('polish:opening-class-balance',polish.includes('BASIC_MUL')&&['mage:1.14','necromancer:1.20','rogue:.80','gunslinger:.73'].every(x=>polish.includes(x)));
check('polish:difficulty-opening',polish.includes('NORMAL:1.18')&&polish.includes('HARD:1.24')&&polish.includes('NIGHTMARE:1.30')&&polish.includes('HELL:1.36')&&polish.includes('openingDiffMul'));
check('polish:easy-unchanged',polish.includes('EASY:1'));
check('polish:rogue-vfx',polish.includes('rogueslash26')&&polish.includes('rogueFxFixed:true'));
check('polish:marker-cleanup',polish.includes("playerMarker:'cornerTicks'")&&polish.includes("shieldIndicator:'hex'"));
check('polish:hud-no-overlap',polish.includes('#buffTracker{right:214px')&&polish.includes('hudNoOverlap:true'));
check('motion:render-only',motion.includes("build:'0.27'")&&motion.includes('renderingOnly:true'));
check('motion:player',motion.includes('playerMotion:true')&&motion.includes('classAttackMotion:true')&&motion.includes('_v27AttackUntil'));
check('motion:enemy',motion.includes('enemyGait:true')&&motion.includes('hitReactions:true')&&motion.includes('enemyTransform'));
check('motion:boss',motion.includes('bossEntrance:true')&&motion.includes('bossPhaseMotion:true')&&motion.includes('phaseAt'));
check('motion:world',motion.includes('biomeAmbience:true')&&motion.includes('nexusMotion:true')&&motion.includes('projectileTrails:true'));
check('motion:ui-mobile',motion.includes('uiMicroMotion:true')&&motion.includes('mobileAdaptiveFx:true')&&motion.includes('prefers-reduced-motion'));
check('party:5p-native',party.includes('MAX_PLAYERS=5')&&party.includes("['p2','p3','p4','p5']")&&party.includes('joinRetry:true')&&party.includes('iceFallback:true'));
check('party:global-level-pause',party.includes("state='partyLevel'")&&party.includes('waitForAllLevelChoices:true')&&party.includes('freezeTimers:true'));
check('party:wait-ui',party.includes('partyLevelStatus28')&&party.includes('SELECTING')&&party.includes('READY'));
check('runtime:0.26-legacy',verify26.includes("build:'0.26'")&&verify26.includes('openingBalance'));
check('runtime:0.27-legacy',verify27.includes("build:'0.27'")&&verify27.includes('bossMotion'));
check('runtime:0.28',verify28.includes("build:'0.28'")&&verify28.includes('fivePlayerLink')&&verify28.includes('party28'));
const failed=results.filter(x=>!x.ok);for(const r of results)console.log(`${r.ok?'PASS':'FAIL'} ${r.name}${r.detail?' · '+r.detail:''}`);console.log(`\n${results.length-failed.length}/${results.length} checks passed`);if(failed.length){console.error('FAILED:',failed.map(x=>x.name).join(', '));process.exit(1)}
