import fs from 'node:fs';
import path from 'node:path';
const root=process.argv[2]||'nexus-survival',read=f=>fs.readFileSync(path.join(root,f),'utf8'),exists=f=>fs.existsSync(path.join(root,f));
const results=[],check=(name,ok,detail='')=>results.push({name,ok:!!ok,detail});
const required=['index.html','manifest.webmanifest','game-core.js','game-multi.js','game-render.js','game-raid-v11.js','game-mobile-v12.js','game-classes-v13.js','game-progression-v13.js','game-balance-fix-v13.js','game-runtime-fix-v14.js','game-spawn-v18.js','game-multiplayer-v19.js','game-visual-v20.js','game-swarm-v21.js','game-power-v22.js','game-buffs-v23.js','game-expansion-v24.js','game-boss-tiers-v24.js','game-verify-v16.js','game-verify-v19.js'];
for(const f of required)check(`file:${f}`,exists(f));
const index=read('index.html'),manifest=JSON.parse(read('manifest.webmanifest')),classes=read('game-classes-v13.js'),progression=read('game-progression-v13.js'),verify=read('game-verify-v16.js'),verify24=read('game-verify-v19.js'),spawnFix=read('game-spawn-v18.js'),multiFix=read('game-multiplayer-v19.js'),visual20=read('game-visual-v20.js'),swarm21=read('game-swarm-v21.js'),power22=read('game-power-v22.js'),buffs=read('game-buffs-v23.js'),exp=read('game-expansion-v24.js'),boss=read('game-boss-tiers-v24.js'),raid=read('game-raid-v11.js'),mobile=read('game-mobile-v12.js');
check('build:0.24',index.includes('BUILD 0.24')&&index.includes('PROTOCOL // 24'));
check('cache:v24',/game-expansion-v24\.js\?v=24/.test(index)&&/game-boss-tiers-v24\.js\?v=24/.test(index)&&/game-verify-v19\.js\?v=24/.test(index));
check('verify:last-script',index.lastIndexOf('game-verify-v19.js')>index.lastIndexOf('game-boss-tiers-v24.js'));
check('mobile:portrait',index.includes('screen-orientation')&&manifest.orientation==='portrait');
check('mobile:7-dashes',['warrior','archer','mage','priest','necromancer','rogue','gunslinger'].every(x=>mobile.includes(`${x}:{name:`))&&mobile.includes('NEXUS_DASH_V24'));
check('raid:telegraphs',raid.includes('function executeTg')&&raid.includes('raidTelegraphs')&&progression.includes('b.raid.cd=999'));
const oldIds=[...classes.matchAll(/\b(BZ|GD|RN|SN|EL|AW|SE|IQ)\d{2}\s*:/g)];check('adv:legacy40',new Set(oldIds.map(m=>m[0])).size===40);
check('progression:50',progression.includes('for(let i=0;i<50;i++)')&&progression.includes('window.NEXUS_MAX_STAGE=50'));
check('progression:milestones',progression.includes("if(s===10){beginAdvancement();return}")&&progression.includes("if(s===30){beginAwakening();return}")&&progression.includes("if(s===50){endGame"));
check('spawn:watchdog',spawnFix.includes('minPopulation')&&spawnFix.includes('spawn(false)'));
check('multi:rewards-dash',multiFix.includes('partyBossRewards:true')&&multiFix.includes('dashClockSync:true'));
check('visual:v20',visual20.includes('monsterSilhouettes:25')&&visual20.includes('bossSilhouettes:15'));
check('swarm:2x-grades',swarm21.includes('spawnMultiplier:2')&&['common','uncommon','rare','epic','legendary'].every(x=>swarm21.includes(`${x}:{name:`))&&swarm21.includes('gradeXp'));
check('power:v22',power22.includes("build:'0.22'")&&power22.includes('const START=1.04')&&power22.includes('const CAP=1.24'));
check('buff:v24',buffs.includes("build:'0.24'")&&buffs.includes('newClassBuffs:true')&&buffs.includes("'_highNoonUntil'")&&buffs.includes("'_immortalArmyUntil'"));
check('exp:3-base-classes',['C.necromancer','C.rogue','C.gunslinger'].every(x=>exp.includes(x)));
check('exp:45-base-skills',[...exp.matchAll(/\b(N\d{2}|R\d{2}|GS\d{2})\s*:/g)].length>=45);
check('exp:6-advancements',['lich','necrolord','assassin','shadowdancer','desperado','artillerist'].every(x=>new RegExp(`\\b${x}:\\{base:`).test(exp)));
check('exp:30-advanced-skills',[...exp.matchAll(/\b(LI|NL|AS|SD|DP|AT)\d{2}\s*:/g)].length>=30);
check('exp:7-base-14-adv',exp.includes('baseClasses:7')&&exp.includes('advancements:14'));
check('exp:5p',exp.includes('maxPlayers:5')&&exp.includes("['p2','p3','p4','p5']")&&exp.includes('NET.conns.size>=4')&&exp.includes('PARTY[5]'));
check('exp:boss-adds',exp.includes('g._bossAddCd')&&exp.includes('if(g.boss)')&&exp.includes('spawn(false)')&&exp.includes('bossAdds:true'));
check('exp:new-ults',['죽음의 일식','망자의 대군세','절명','그림자 난무','하이 눈','전면 포격'].every(x=>exp.includes(x)));
check('boss:mid-stages',boss.includes('midStages:[5,15,25,35,45]')&&boss.includes("s%5===0?'mid'"));
check('boss:major-stages',boss.includes('majorStages:[10,20,30,40,50]')&&boss.includes("s%10===0?'major'"));
check('boss:tier-stats',boss.includes('boss.max*=1.38')&&boss.includes('boss.max*=1.65')&&boss.includes('boss.dmg*=1.18'));
check('boss:pattern-counts',boss.includes('midPatterns:4')&&boss.includes('majorPatterns:5')&&boss.includes('castMid')&&boss.includes('castMajor'));
check('boss:network-tier',boss.includes('d.bossTier=e.bossTier')&&boss.includes('e.bossTier=d.bossTier'));
check('boss:adds-continue',boss.includes('addsContinue:true'));
check('fix:transient-cleanup',verify.includes('_smoothDash')&&verify.includes('_rangerUltUntil'));
check('runtime:self-qa-24',verify24.includes("build:'0.24'")&&verify24.includes('sevenBaseClasses')&&verify24.includes('fourteenAdvancements')&&verify24.includes('maxPlayers5')&&verify24.includes('bossTierBuild'));
const failed=results.filter(x=>!x.ok);for(const r of results)console.log(`${r.ok?'PASS':'FAIL'} ${r.name}${r.detail?' · '+r.detail:''}`);console.log(`\n${results.length-failed.length}/${results.length} checks passed`);if(failed.length){console.error('FAILED:',failed.map(x=>x.name).join(', '));process.exit(1)}