import puppeteer from 'puppeteer-core';
const base=process.env.NEXUS_QA_URL||'http://127.0.0.1:4173/';
const expectedBuild=process.env.NEXUS_EXPECTED_BUILD||'0.25';
const chrome=process.env.CHROME_BIN||'/usr/bin/google-chrome';
const browser=await puppeteer.launch({headless:true,executablePath:chrome,protocolTimeout:30000,args:['--no-sandbox','--disable-dev-shm-usage','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const fail=(m,d='')=>{throw new Error(`${m}${d?' :: '+d:''}`)},mark=s=>console.log('V24 QA :: '+s);
async function open(label){const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push('pageerror: '+e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push('console: '+m.text())});await p.setViewport({width:1280,height:720});await p.goto(base,{waitUntil:'domcontentloaded',timeout:30000});await p.waitForFunction(build=>window.NEXUS_RUNTIME_CHECK?.build===build,{timeout:12000},expectedBuild);const q=await p.evaluate(()=>window.NEXUS_RUNTIME_CHECK);if(!q.ok)fail(label+' runtime',JSON.stringify(q.failed));return{p,errors}}
try{
 const a=await open('class');const p=a.p;
 const defs=await p.evaluate(()=>({classes:Object.keys(C),lens:{necromancer:Object.keys(SK.necromancer||{}).length,rogue:Object.keys(SK.rogue||{}).length,gunslinger:Object.keys(SK.gunslinger||{}).length},adv:Object.keys(window.NEXUS_ADV||{}),exp:window.NEXUS_EXPANSION_V24,dash:window.NEXUS_DASH_V24,boss:window.NEXUS_BOSS_TIERS_V24}));
 if(defs.classes.length<7||defs.lens.necromancer!==15||defs.lens.rogue!==15||defs.lens.gunslinger!==15||defs.adv.length<14||defs.exp.maxPlayers!==5||defs.dash.classes.length<7)fail('class definitions',JSON.stringify(defs));mark('7 base / 14 advancement definitions PASS');
 await p.evaluate(()=>{cls='necromancer';NET.mode='solo';NET.localId='p1';startRun()});await p.waitForFunction(()=>eval("state==='play'&&localPlayer()?.cls==='necromancer'"),{timeout:3000});
 await p.evaluate(()=>eval(`(()=>{g.e=[];g.boss=false;spawn(false);const q=localPlayer();q.skills={N01:1,N03:1,N09:1,N15:1};q.cd={N01:-1,N03:-1,N09:-1,N15:-1};runSkills(q,.016)})()`));mark('necromancer base combat PASS');
 await p.evaluate(()=>eval(`(()=>{g.stage=9;g.e=[];g.boss=false;state='play';openChest()})()`));await p.waitForFunction(()=>eval("state==='advancement'&&document.querySelectorAll('#advCards .advanceCard').length===2"),{timeout:3000});const advText=await p.evaluate(()=>document.getElementById('advCards').textContent);if(!advText.includes('리치')||!advText.includes('네크로 로드'))fail('necromancer advancement cards',advText);await p.evaluate(()=>document.querySelector('#advCards .advanceCard')?.click());await p.waitForFunction(()=>eval("state==='play'&&g.stage===10&&localPlayer().subclass==='lich'"),{timeout:3000});mark('stage 10 necromancer advancement PASS');
 await p.evaluate(()=>eval(`(()=>{g.stage=29;g.e=[];g.boss=false;state='play';openChest()})()`));await p.waitForFunction(()=>eval("state==='awakening'&&localPlayer().awakened"),{timeout:3000});await p.evaluate(()=>document.getElementById('advContinue')?.click());await p.waitForFunction(()=>eval("state==='play'&&g.stage===30"),{timeout:3000});const ult=await p.evaluate(()=>eval(`(()=>{const q=localPlayer();q.ultReadyAt=g.t;const ok=window.nexusUseUlt(q,false);return {ok,ready:q.ultReadyAt-g.t,sub:q.subclass}})()`));if(!ult.ok||ult.ready<50)fail('new ultimate',JSON.stringify(ult));mark('new awakening / ultimate PASS');if(a.errors.length)fail('class browser errors',a.errors.join(' | '));await p.close();

 const b=await open('5p');const h=b.p;
 const join=await h.evaluate(()=>eval(`(()=>{NET.mode='host';NET.ready=true;NET.localId='p1';NET.lobby={p1:{id:'p1',cls:'warrior',name:'HOST'}};NET.inputs={};NET.conns=new Map();const out=[];for(const [i,c] of ['necromancer','rogue','gunslinger','priest'].entries()){const conn={peer:'qa'+i,open:true,playerId:null,send:m=>out.push({i,m})};NET.conns.set(conn.peer,conn);netHostMessage(conn,{t:'join',cls:c})}const extra={peer:'qaX',open:true,playerId:null,send:m=>out.push({i:9,m})};netHostMessage(extra,{t:'join',cls:'mage'});return {ids:Object.keys(NET.lobby).sort(),classes:Object.values(NET.lobby).map(x=>x.cls),full:out.some(x=>x.i===9&&x.m.t==='full')}})()`));if(join.ids.join(',')!=='p1,p2,p3,p4,p5'||!join.full)fail('5p join assignment',JSON.stringify(join));mark('5 player lobby capacity PASS');
 await h.evaluate(()=>eval('startRun()'));await h.waitForFunction(()=>eval("state==='play'&&partyCount()===5&&Object.keys(g.players).length===5"),{timeout:3000});const five=await h.evaluate(()=>eval(`(()=>({pc:partyCount(),ids:Object.keys(g.players).sort(),classes:Object.values(g.players).map(p=>p.cls),net:makeNetState().players.length,p5col:playerRingColor('p5')}))()`));if(five.pc!==5||five.net!==5||five.ids.join(',')!=='p1,p2,p3,p4,p5'||five.p5col!=='#74f0c4')fail('5p run',JSON.stringify(five));mark('5 player run/network state PASS');
 await h.evaluate(()=>eval(`(()=>{g.e=[];g.boss=false;spawn(false);const by=Object.values(g.players);for(const q of by){if(q.cls==='necromancer'){q.skills={N01:1,N04:1};q.cd={N01:-1,N04:-1}}if(q.cls==='rogue'){q.skills={R01:1,R04:1};q.cd={R01:-1,R04:-1}}if(q.cls==='gunslinger'){q.skills={GS02:1,GS07:1};q.cd={GS02:-1,GS07:-1}}runSkills(q,.016)}})()`));mark('new class 5P combat smoke PASS');
 const mid=await h.evaluate(()=>eval(`(()=>{g.stage=4;g.t=0;g.e=[];g.q=[];g.fx=[];g.raidTelegraphs=[];g.boss=false;g._bossAddCd=0;spawn(true);const b=g.e.find(e=>e.boss);b._tierPatternCd=0;const before=g.e.filter(e=>!e.boss).length;updateHost(1/60);const after=g.e.filter(e=>!e.boss).length;return {tier:b.bossTier,hp:b.max,dmg:b.dmg,r:b.r,addsBefore:before,addsAfter:after,tg:g.raidTelegraphs.filter(t=>t.bossId===b.id).length}})()`));if(mid.tier!=='mid'||mid.addsAfter<=mid.addsBefore||mid.tg<4)fail('mid boss',JSON.stringify(mid));mark(`stage 5 MID BOSS PASS adds=${mid.addsAfter} patterns=${mid.tg}`);
 const major=await h.evaluate(()=>eval(`(()=>{g.stage=9;g.t=0;g.e=[];g.q=[];g.fx=[];g.raidTelegraphs=[];g.boss=false;g._bossAddCd=0;spawn(true);const b=g.e.find(e=>e.boss);b._tierPatternCd=0;let maxTg=0;updateHost(1/60);maxTg=Math.max(maxTg,g.raidTelegraphs.filter(t=>t.bossId===b.id).length);const firstAdds=g.e.filter(e=>!e.boss).length;g._bossAddCd=0;for(let i=0;i<90;i++){updateHost(1/60);maxTg=Math.max(maxTg,g.raidTelegraphs.filter(t=>t.bossId===b.id).length)}const secondAdds=g.e.filter(e=>!e.boss).length;return {tier:b.bossTier,hp:b.max,dmg:b.dmg,r:b.r,firstAdds,secondAdds,maxTg,casts:b._majorCastNo||0,label:(document.getElementById('bname')?.textContent||'')}})()`));if(major.tier!=='major'||major.firstAdds<1||major.secondAdds<=major.firstAdds||major.maxTg<5||major.casts<1||!major.label.includes('STAGE BOSS'))fail('major boss',JSON.stringify(major));mark(`stage 10 STAGE BOSS PASS adds ${major.firstAdds}->${major.secondAdds} patterns=${major.maxTg}`);
 if(!(major.hp>mid.hp*1.2)&&major.dmg<=mid.dmg)fail('boss tier scaling',JSON.stringify({mid,major}));
 if(b.errors.length)fail('5p browser errors',b.errors.join(' | '));await h.close();
 console.log('PASS v24: 7 classes / 14 advancements / 5P / mid+major bosses / boss add spawning');console.log('6/6 focused v24 groups passed');
}finally{await browser.close().catch(()=>{})}
